l10n_it_ricevute_bancarie/__openerp__.py
l10n_it_ricevute_bancarie/account/account.py
l10n_it_ricevute_bancarie/account/account_view.xml
l10n_it_ricevute_bancarie/demo/riba_demo.xml
l10n_it_ricevute_bancarie/riba.py
l10n_it_ricevute_bancarie/test/issue_riba.yml
l10n_it_ricevute_bancarie/test/riba_invoice.yml
l10n_it_ricevute_bancarie/test/unsolved_riba.yml
l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py

Ported from https://code.launchpad.net/~bruno-bottacini/openobject-italia/6.1-fix-bug-1167773/+merge/158863

7.0 RiBa improvemente. Unsolved RiBa improvements; RiBa list to be issued; tests

---

.travis.yml
README.md
oca_dependencies.txt

This PR is related to https://github.com/OCA/maintainer-quality-tools/issues/194

Update travis for branch 8.0

---

README.md

According to https://github.com/OCA/maintainer-quality-tools/pull/196

Use svg badge for coveralls

---

l10n_it_ipa/README.rst
l10n_it_rea/README.rst

https://github.com/OCA/maintainer-tools/pull/59

Add bug tracker link on README.rst

---

l10n_it_pec/view/partner_view.xml

adding pec_mail field in tree and kanban view

[IMP] mail_pec field in list and kanban view

---

account_invoice_entry_date/views/account_view.xml

supplier invoices only.
See https://github.com/OCA/l10n-italy/pull/106#issuecomment-118976044

[FIX] making the 'registration date' field visible for

---

account_invoice_entry_date/models/account.py

The invoice date cannot be later than the date of registration

FIX after duplicating an old invoice and validating it, get

---

l10n_it_ricevute_bancarie/views/wizard_riba_file_export.xml
l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py

FIX https://github.com/OCA/l10n-italy/issues/165

---

l10n_it_account/reports/account_reports_view.xml

Adjust header markup into l10n_it_account.internal_layout to ease customization from 3rd party modules.

[imp] l10n_it_account.internal_layout: better report header markup

---

l10n_it_fatturapa_out/tests/data/IT06363391001_00004.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

According to http://rispondipa.it/516/quale-importo-totale-documento

Fix ImportoTotaleDocumento: it must further include the tax amount

---

l10n_it_ricevute_bancarie/models/account/account.py
l10n_it_ricevute_bancarie/tests/test_invoice_due_cost.py

Fix riba unreconcile

---

l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py

to make green 8.0 at https://travis-ci.org/OCA/l10n-italy/branches

FIX W503 line break before binary operator

---

l10n_it_ddt/data/ddt_data.xml

no_gap implementation for default

[FIX] ddt sequence

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/security/security.xml
l10n_it_ddt/views/stock_picking_package_preparation.xml

In MultiCompany is useful to have different sequences for the some document. DDT sequence is defined on DDT Type. So, ddt type would be multi company compatible.

8.0 ddt type multy company

---

l10n_it_ricevute_bancarie/__openerp__.py
l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py

[imp] abi cab from bank if no iban specified

---

l10n_it_ddt/data/ddt_data.xml
l10n_it_ddt/views/report_ddt.xml

I'll update italian translation on transifex soon
this replace PR #212

Some terms translated to english for better consistency

---

l10n_it_base_location_geonames_import/__openerp__.py

Tested it on odoo 9.0 by using this PR https://github.com/OCA/partner-contact/pull/231.
It works... anything else to do here?

[9.0][WIP] l10n_it_base_location_geonames_import on 9.0

---

l10n_it_ddt/wizard/ddt_from_picking.py

PR for https://github.com/OCA/l10n-italy/issues/215

[FIX] Get partners for ddt from origin sale of picking

---

l10n_it_ricevute_bancarie/models/account/account.py
l10n_it_ricevute_bancarie/models/riba.py

Fix riba reconciliation and make tests green

---

l10n_it_corrispettivi/account.py
l10n_it_corrispettivi/account_view.xml

[8.0] FIX l10n_it_corrispettivi

---

l10n_it_ddt/views/report_ddt.xml

better delivery data in qweb report

8.0 ddt extend delivery data

---

l10n_it_ddt/views/stock_picking_package_preparation.xml

hide "create invoice" button if ddt has invoice_id

[8.0][l10n_it_ddt] hide 'create invoice' button if ddt has invoice_id

---

l10n_it_ricevute_bancarie/i18n/it.po
l10n_it_ricevute_bancarie/models/riba.py
l10n_it_ricevute_bancarie/views/riba_view.xml

aggiunge alla distinta la possibilità di gestire data accettazione e data accredito

data accettazione e data accredito modificabili

---

l10n_it_ddt/README.rst
l10n_it_ddt/i18n/it.po
l10n_it_ddt/tests/test_ddt.py
l10n_it_ddt/wizard/ddt_create_invoice.py
l10n_it_ddt/wizard/ddt_create_invoice.xml

Now we are able to create invoices grouping ddt by partner

[8.0][DDT] invoice wizard groups ddt by partner

---

l10n_it_base_location_geonames_import/__manifest__.py
l10n_it_base_location_geonames_import/geonames_import.py
l10n_it_base_location_geonames_import/test/import.yml

WIP l10n_it_base_location_geonames_import migrated to 10.0

[MIG] l10n_it_base_location_geonames_import: Migrated to 10.0

---

account_invoice_entry_date/models/account.py

When an in invoice or refund has a registration date, the invoice sequence must be based on registration date year

8.0 - account_invoice_entry_date - Invoice sequence based on registration_date

---

l10n_it_ddt/views/stock_picking_package_preparation.xml

useful to filter different kinds of DDT

[add] ddt type filter

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py
l10n_it_ddt/views/stock_picking_package_preparation.xml

Ho aggiunto un metodo che calcola il peso sul ddt anche se non su sa il package ma si passa dal picking

[FIX] Fix weight on ddt from pickings

---

l10n_it_corrispettivi/account_view.xml

[FIX] Add partner on search view

---

l10n_it_ddt/i18n/it.po
l10n_it_ddt/views/stock_picking_package_preparation.xml
l10n_it_ddt/wizard/ddt_invoicing.py

Sono state aggiunte le seguenti migliorie:
- Potranno essere fatturati solo i ddt nello stato di completato.
- Aggiunto filtro per ddt fatturato, da fatturare e in bozza
- Aggiunto raggruppamento per data ddt, tipo ddt, stato

10.0 l10n it ddt invoicing enhanced

---

l10n_it_ricevute_bancarie/__openerp__.py
l10n_it_ricevute_bancarie/models/riba.py
l10n_it_ricevute_bancarie/views/riba_detail_view.xml

aggiunta tree con dettaglio righe di ogni distinta, per facilitare la ricerca soprattutto degli insoluti

[8.0] riba migliore ricerca dettagli 

---

l10n_it_ricevute_bancarie/views/riba_detail_view.xml

[FIX]  l10n_it_ricevute_bancarie: fix typo

---

l10n_it_codici_carica/README.rst
l10n_it_codici_carica/__init__.py
l10n_it_codici_carica/__manifest__.py
l10n_it_codici_carica/data/codici_carica_data.xml
l10n_it_codici_carica/i18n/it.po
l10n_it_codici_carica/models/__init__.py
l10n_it_codici_carica/models/codice_carica.py
l10n_it_codici_carica/security/ir.model.access.csv
l10n_it_codici_carica/views/codice_carica_view.xml

Corretti conflitti
Fix conflitti

10.0-Tabella codici carica da usare nei dichiarativi fiscali

---

account_vat_period_end_statement/report/vat_period_end_statement.py
l10n_it_account/models/account_tax.py

move _get_tax_codes_amounts to l10n_it_account to make it reusable

REF account_vat_period_end_statement

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py
l10n_it_ddt/views/stock_picking_package_preparation.xml

it's necessary to check if a picking in 'picking_ids' is 'done'. if so, the button 'put in pack'(in the header) will be invisible

[ADD] l10n_it_ddt new field boolean

---

l10n_it_fiscalcode/view/fiscalcode_view.xml

from field individual in l10n_it_fiscalcode

[FIX][8.0] remove not existing group group_extended

---

l10n_it_account/__manifest__.py
l10n_it_account/i18n/it.po
l10n_it_account/views/account_setting.xml

[ADD] Add new menu 'Italian Localization' and translate to 'Fiscalità Italiana' in it.po

[ADD] Add new menu and translate

---

l10n_it_regions/README.rst
l10n_it_regions/__init__.py
l10n_it_regions/__openerp__.py
l10n_it_regions/i18n/it.po
l10n_it_regions/i18n/l10n_it_regions.pot
l10n_it_regions/models/__init__.py
l10n_it_regions/models/partner.py
l10n_it_regions/models/region.py
l10n_it_regions/security/ir.model.access.csv
l10n_it_regions/views/partner_view.xml
l10n_it_regions/views/region_view.xml
l10n_it_regions/wizards/__init__.py
l10n_it_regions/wizards/geonames_import.py

8.0 regions scigghia

---

l10n_it_fiscal_document_type/README.rst
l10n_it_fiscal_document_type/model/__init__.py
l10n_it_fiscal_document_type/model/account_invoice.py
l10n_it_fiscal_document_type/model/fiscal_document_type.py
l10n_it_fiscal_document_type/model/journal.py

Check m2m relation that is actually a o2m (1 journal can only link to 1 doc type)
Fix partner and journal onchange to correctly retrieve doc type

FIX l10n_it_fiscal_document_type

---

l10n_it_vat_registries/vat_registry.py

Visualizzazione nel registro IVA delle imposte con iva inclusa nel prezzo.
Nel caso in cui due imposte (una con iva inclusa nel prezzo e una con iva esclusa dal prezzo), utilizzino lo stesso account tax code o lo stesso account base code, verrà utilizzata solo quella con iva esclusa dal prezzo.

8.0 l10n it vat registries fix price include

---

README.md

8.0: https://github.com/OCA/l10n-italy/pull/396
9.0: https://github.com/OCA/l10n-italy/pull/397
11.0: https://github.com/OCA/l10n-italy/pull/398

[10.0] IMP repo README with mailing list

---

l10n_it_ddt/views/stock_picking_package_preparation.xml

adds ddt_type in tree view
adds group by ddt type in search

[8.0] DDT ddt type in tree and in search

---

account_vat_period_end_statement/__manifest__.py
account_vat_period_end_statement/i18n/it.po
account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/views/account_view.xml
account_vat_period_end_statement/views/report_vatperiodendstatement.xml

ADD interessi dovuti e modifica del loro calcolo + FIX ValueError: Expected singleton: account.vat.period.end.statement(1, 2, 4, 6, 7, 8, 9, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27)

[10.0] account_vat_period_end_statement ADD crediti d'imposta

---

l10n_it_vat_registries/__manifest__.py
l10n_it_vat_registries/models/vat_registry.py
l10n_it_vat_registries/report/reports.xml
l10n_it_vat_registries/wizard/print_registro_iva.py
l10n_it_vat_registries_cash_basis/README.rst
l10n_it_vat_registries_cash_basis/__init__.py
l10n_it_vat_registries_cash_basis/__manifest__.py
l10n_it_vat_registries_cash_basis/models/__init__.py
l10n_it_vat_registries_cash_basis/models/account.py
l10n_it_vat_registries_cash_basis/models/vat_registry.py
l10n_it_vat_registries_cash_basis/tests/__init__.py
l10n_it_vat_registries_cash_basis/tests/test_registry.py
l10n_it_vat_registries_cash_basis/wizard/__init__.py
l10n_it_vat_registries_cash_basis/wizard/print_registro_iva.py

nuovo modulo registro iva per cassa

[10] gestione del registro iva con iva per cassa

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/wizard/ddt_invoicing.xml

Corregge il caso di raggruppamento di ddt non generati da ordini di vendita->ordini di consegna

10 l10n it ddt fix grouping

---

account_invoice_report_ddt_group/README.rst
account_invoice_report_ddt_group/__manifest__.py
account_invoice_report_ddt_group/i18n/it.po
account_invoice_report_ddt_group/models/__init__.py
account_invoice_report_ddt_group/models/account_invoice.py
account_invoice_report_ddt_group/models/partner.py
account_invoice_report_ddt_group/tests/test_invoice_ddt_group.py
account_invoice_report_ddt_group/views/invoice_ddt.xml
account_invoice_report_ddt_group/views/partner.xml
l10n_it_ddt/data/ddt_data.xml
l10n_it_ddt/models/stock_picking_package_preparation.py

Ordina i ddt della fattura di fine mese in base al numero.
Nel riferimento aggiunge la dicitura "DDT" se non è  presente nel numero del DDT

10.0 invoice report ddt group order and label

---

l10n_it_reverse_charge/__manifest__.py
l10n_it_reverse_charge/tests/__init__.py
l10n_it_reverse_charge/tests/test_rc.py

Hi, 
added a few tests to reverse_charge module

[ADD] reverse charge tests

---

account_vat_period_end_statement/tests/test_vat_statement.py

In cases like today, feb 28, no date range is found

FIX account_vat_period_end_statement tests

---

l10n_it_fiscal_document_type/data/fiscal.document.type.csv

v. http://www.agenziaentrate.gov.it/wps/content/nsilib/nsi/normativa+e+prassi/provvedimenti/2018/febbraio+2018+provvedimenti/provvedimento+05022018+dati+fattura

[IMP] fiscal document type TD12

---

l10n_it_ricevute_bancarie/models/riba.py

Fixes the error message when moving riba lines back to draft

[10.0][FIX][riba] Fix when moving to draft state all riba lines

---

l10n_it_ddt/README.rst
l10n_it_ddt/__manifest__.py
l10n_it_ddt/models/stock_picking_package_preparation.py

It is important to call sale.order.line._prepare_invoice_line in order to not break inheritance
For example , without this, modules stock_picking_invoice_link and sale_commission would not work

FIX l10n_it_ddt: _prepare_invoice_line

---

l10n_it_corrispettivi/__manifest__.py
l10n_it_corrispettivi/models/account.py
l10n_it_corrispettivi/views/account_view.xml

Corrispettivi form prints the report dedicated to corrispettivi (report_corrispettivi).
I've also set the corrispettivi form's as primary in order to easily allow further modifications without interfering with invoice's form.

[IMP] print button in corrispettivi prints his own report

---

l10n_it_fiscalcode/migrations/10.0.1.0.1/post-migrate.py

Nel caso di poche migliaia di partner (6000), la post migration richiede un tempo esponenziale.

[10.0] Fix l10n_it_fiscalcode performance migration

---

l10n_it_codici_carica/models/codice_carica.py

https://www.odoo.com/documentation/10.0/howtos/backend.html#model-constraints

[10.0] FIX  l10n_it_codici_carica api.constrains gets a recordset

---

l10n_it_account_tax_kind/__manifest__.py
l10n_it_account_tax_kind/model/account_tax_kind.py

Porting https://github.com/OCA/l10n-italy/pull/557 to v11

[FIX] l10n_it_account_tax_kind display_name

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/security/security.xml
l10n_it_ddt/views/stock_picking_package_preparation.xml

This covers the following use case:
1. User in Company1: Define the ddt.type *DDT_type* and bind that to a sequence *DDT_seq*;
2. User in Company2: Create new delivery order and place it in a new DDT of type *DDT_type*;
3. User in Company2: 'Put in pack'
Behavior before this PR:
```
The requested operation cannot be completed due to security restrictions.
Please contact your system administrator.
(Document type: ir.sequence, Operation: read, Records: 28, User: 10)
```
Behavior after this PR:
Package created

[ADD] DDT type multi-company

---

.travis.yml

Following on the thread: OCA/account-financial-reporting#468 (comment)

[FIX] .travis.yml: remove duplicated postgresql line

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/company.py
l10n_it_fatturapa/models/partner.py
l10n_it_fatturapa/views/partner_view.xml
l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/views/partner_view.xml

useless field
supplier fields only visible for suppliers
Check mandatory customer fields before exporting XML
Prevent to use sequence already used by journals

[10.0] IMP l10n_it_fatturapa interface

---

l10n_it_ricevute_bancarie/models/riba.py

Fix UnicodeEncodeError: 'ascii' codec can't encode character lettura nome del partner in composizione stringa funzionalità SETTLE ALL in distinta Riba

[10.0][FIX] l10n_it_ricevute_banacarie-UnicodeEncodeError

---

l10n_it_fatturapa_out_ddt/__manifest__.py
l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa_view.xml

[10.0][FIX] l10n_it_fatturapa_out_ddt: wizard popup

---

l10n_it_fatturapa_out/README.rst
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/models/account.py
l10n_it_fatturapa_out/models/attachment.py
l10n_it_fatturapa_out/readme/CONFIGURE.rst
l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
l10n_it_fatturapa_out/readme/DESCRIPTION.rst
l10n_it_fatturapa_out/readme/USAGE.rst
l10n_it_fatturapa_out/static/description/index.html
l10n_it_fatturapa_out/views/account_view.xml
l10n_it_fatturapa_out/views/attachment_view.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[IMP] revamp README and manifest

[FIX] change FatturaPA into E-invoice

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/__init__.py
l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
l10n_it_fatturapa_pec/models/fetchmail.py
l10n_it_fatturapa_pec/views/fetchmail_view.xml

While sending, check for valid fetchmail server

l10n_it_fatturapa_pec: check possible fetch errors and track them

---

l10n_it_fiscal_document_type/data/fiscal.document.type.csv

* [IMP] add all TD** known
See https://github.com/OCA/l10n-italy/pull/671

[11.0] add TD12 document type (#671)

---

l10n_it_fiscal_document_type/data/fiscal.document.type.csv

* [IMP] add all TD** known
https://github.com/OCA/l10n-italy/pull/671

[12.0] add TD12 document type (#671)

---

l10n_it_fatturapa_out/views/account_view.xml

[10.0] invoice can be exported to xml even in paid state 

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fiscal_document_type/__manifest__.py
l10n_it_fiscal_document_type/data/fiscal.document.type.csv
l10n_it_fiscal_document_type/models/account_invoice.py
l10n_it_fiscal_document_type/tests/test_doc_type.py

IMP l10n_it_fiscal_document_type to be sure that doc type is always set
FIX l10n_it_fatturapa_out to use the fiscal doc type
TODO
v12: https://github.com/OCA/l10n-italy/pull/725

[10.0] ADD TD20 doc type

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fiscal_document_type/__manifest__.py
l10n_it_fiscal_document_type/data/fiscal.document.type.csv
l10n_it_fiscal_document_type/models/account_invoice.py
l10n_it_fiscal_document_type/tests/test_doc_type.py

IMP l10n_it_fiscal_document_type to be sure that doc type is always set
FIX l10n_it_fatturapa_out to use the fiscal doc type

[12.0] ADD TD20 doc type

---

l10n_it_fatturapa/models/partner.py

[10.0] remove state_id constrains

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[10.0] latin for Descrizione invoice line and RiferimentoNormativo tax

---

l10n_it_fatturapa/models/partner.py

[8.0] remove state_id check

---

l10n_it_withholding_tax/views/account.xml

For compatibility with other modules

[8.0] [IMP] view more specific xpath

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[12.0] latin type encode

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/security/ir.model.access.csv

Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Administration/Settings
(Document model: fetchmail.server)
TODO
v12

[10.0] FIX l10n_it_fatturapa_pec: sending PEC with invoicing user raises permission error

---

l10n_it_fatturapa_out_stamp/__manifest__.py
l10n_it_fatturapa_out_stamp/wizard/wizard_export_fatturapa.py

Fix https://github.com/OCA/l10n-italy/issues/769

[10.0][FIX] l10n_it_fatturapa_out_stamp: Bollo precision must be 2

---

l10n_it_fatturapa/bindings/__init__.py

[FIX] import of fatturapa_v_1_1 to fatturapa_v_1_2 that cause debug error due to changed file name

[8.0][FIX] l10n_it_fatturapa

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/account.py
l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/account_view.xml
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

From v10: https://github.com/OCA/l10n-italy/pull/703

[12.0] FIX l10n_it_fatturapa_in: do not automatically add Bollo and cassa previdenziale as invoice line

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

In this case you wuold get
Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}QuantitaType pattern constraint violated by value 2

[12.0] FIX l10n_it_fatturapa_out when decimal precision is < 2

---

l10n_it_fatturapa/models/ir_attachment.py

Add -nosigs option in decryption command (no message signature verification).
openssl (v.1.1.0x) fails to verify signature on some files giving an error like this:
140093892985280:error:04091068:rsa routines:int_rsa_verify:bad signature:../crypto/rsa/rsa_sign.c:220:
140093892985280:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:../crypto/pkcs7/pk7_doit.c:1035:
140093892985280:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:../crypto/pkcs7/pk7_smime.c:353:
Affected versions:
1.1.0f-3+deb9u2 - Debian 9
1.1.0g-2ubuntu4.3 - Ubuntu 18.04
It's quite urgent, it prevents Odoo from loading some xml signed files as well as importing them as invoices.
It supersedes #788

[12.0] [FIX] openssl signature verification error

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/account.py
l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/account_view.xml
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

if charged to customer it will be added as invoice line
TODO
~~v12~~ https://github.com/OCA/l10n-italy/pull/757

[10.0] FIX l10n_it_fatturapa_in: do not automatically add Bollo as invoice line

---

l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py

[8.0][FIX] fatturapa pec reponse unicode

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/views/invoice_view.xml

Allow to manage more-than-one invoice sequence in an invoicing-only environment.
Please review.

[12.0] [IMP] l10n_fatturapa: allow multiple invoice sequence

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[8.0][FIX] set max lenght for attachment name

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[11.0] FIX l10n_it_fatturapa_out when using an invoice address

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/bindings/fatturapa_v_1_2.py
l10n_it_fatturapa/data/fatturapa_data.xml
l10n_it_fatturapa/models/account.py
l10n_it_fatturapa/models/company.py
l10n_it_fatturapa/models/ir_attachment.py
l10n_it_fatturapa/models/partner.py
l10n_it_fatturapa/views/account_view.xml
l10n_it_fatturapa/views/company_view.xml
l10n_it_fatturapa/views/invoice_view.xml

FIX openssl signature verification error
IMP l10n_fatturapa: allow multiple invoice sequence
FIX l10n_it_fatturapa allowing to import XML elements with blank spac
FIX translation source strings l10n_it_fatturapa

[11.0] FIX l10n_it fattuapa: translation, importing XML;(signed with CAdES - elements with blank spac)

---

l10n_it_fatturapa/__openerp__.py
l10n_it_fatturapa/models/ir_attachment.py

[8.0][FIX] openssl signature verification error

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/security/rules.xml
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/security/rules.xml
l10n_it_fatturapa_pec/README.rst
l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/__init__.py
l10n_it_fatturapa_pec/models/company.py
l10n_it_fatturapa_pec/models/mail_thread.py
l10n_it_fatturapa_pec/readme/CONFIGURE.rst
l10n_it_fatturapa_pec/static/description/index.html
l10n_it_fatturapa_pec/views/company_view.xml
l10n_it_sdi_channel/__manifest__.py
l10n_it_sdi_channel/models/sdi.py
l10n_it_sdi_channel/views/sdi_view.xml

TODO
v12: https://github.com/OCA/l10n-italy/pull/877

[10.0] e-invoice multi company

---

l10n_it_fiscalcode/__manifest__.py
l10n_it_fiscalcode/model/__init__.py
l10n_it_fiscalcode/model/res_company.py
l10n_it_fiscalcode/view/company_view.xml

Fixes https://github.com/OCA/l10n-italy/issues/808

[12.0] IMP l10n_it_fiscalcode company view: allow to specify company fiscal code

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/data/fetchmail_data.xml
l10n_it_fatturapa_pec/models/fetchmail.py
l10n_it_fatturapa_pec/views/fetchmail_view.xml

Retry N (configurable) times before resetting fetchmail server.
Notify contacts about reset

[12.0] IMP l10n_it_fatturapa_pec avoiding to block fetchmail server in case of temporary errors

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/data/IT05979361218_010.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

[12.0] FIX: l10n_it_fatturapa_in parsing DatiFattureCollegate

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/data/IT05979361218_010.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

[10.0] FIX: l10n_it_fatturapa_in parsing DatiFattureCollegate

---

l10n_it_fatturapa_in/__openerp__.py
l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Original pdf (if present) is always useful
v. 10 #950 
TODO
later versions

[8.0][IMP] extract pdf if in e-invoice if only linked

---

l10n_it_fiscalcode/__manifest__.py
l10n_it_fiscalcode/model/__init__.py
l10n_it_fiscalcode/model/res_company.py
l10n_it_fiscalcode/view/company_view.xml

Fixes https://github.com/OCA/l10n-italy/issues/808
v12: https://github.com/OCA/l10n-italy/pull/844

[10.0] IMP l10n_it_fiscalcode company view: allow to specify company fiscal code

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/partner.py
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

l10n_it_fatturapa: persons without lastname or firstname can have 'company_name'
v11: https://github.com/OCA/l10n-italy/pull/951
v12: https://github.com/OCA/l10n-italy/pull/936

[10.0] l10n_it_fatturapa_out: use company_name for Denominazione, when present

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

[IMP] unify function extract attachments
[FIX] remove unused import

[10.0][IMP] extract pdf if in e-invoice in only linked

---

l10n_it_fatturapa_pec/README.rst
l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py
l10n_it_fatturapa_pec/readme/CONFIGURE.rst
l10n_it_fatturapa_pec/security/groups.xml
l10n_it_fatturapa_pec/static/description/index.html
l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml

Only 'Allow to force e-invoice export state' group can
TODO
altre versioni
v12: https://github.com/OCA/l10n-italy/pull/935

[10.0] IMP l10n_it_fatturapa_pec allowing to force the XML export state.

---

l10n_it_fiscal_document_type/README.rst
l10n_it_fiscal_document_type/readme/CONFIGURE.rst
l10n_it_fiscal_document_type/static/description/index.html

TODO
versioni successive
V.10 #917

[8.0] add fiscal note for autoinvoices

---

l10n_it_fiscal_document_type/README.rst
l10n_it_fiscal_document_type/readme/CONFIGURE.rst
l10n_it_fiscal_document_type/static/description/index.html

[FIX] readme format
[FIX] improve readme

[10.0] add fiscal note for autoinvoices

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/partner.py
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

l10n_it_fatturapa: persons without lastname or firstname can have 'company_name'

[12.0] l10n_it_fatturapa_out: use company_name for Denominazione, when present

---

l10n_it_fatturapa/__openerp__.py
l10n_it_fatturapa/models/ir_attachment.py
l10n_it_fatturapa_in/__openerp__.py
l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml

[8.0] [FIX] handle invalid URI

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/partner.py

Ref https://github.com/OCA/l10n-italy/pull/979#issuecomment-462143590

[12.0] IMP l10n_it_fatturapa better label 'Enable electronic invoicing' to identify partners

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

From https://github.com/OCA/l10n-italy/pull/950

[12.0] [IMP] extract pdf from e-invoice while linking to odoo invoice

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

[10.0] IMP l10n_it_fatturapa_in using supplier payment term to compute due date

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[10.0] FIX l10n_it_fatturapa_out exporting REA data: if StatoLiquidazione is not valorized, don't export IscrizioneREA

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

while importing lines with price 0 and discount 0
See test
v11: https://github.com/OCA/l10n-italy/pull/1023
v12: https://github.com/OCA/l10n-italy/pull/1024

[10.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

From https://github.com/OCA/l10n-italy/pull/943

[12.0] FIX l10n_it_fatturapa_out for invoices with payment term and total = 0

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

From https://github.com/OCA/l10n-italy/pull/876

[12.0] FIX l10n_it_fatturapa_out exporting REA data: if StatoLiquidazione is not valorized, don't export IscrizioneREA

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

while importing lines with price 0 and discount 0
See test

[11.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

while importing lines with price 0 and discount 0
See test

[12.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero

---

l10n_it_fatturapa_in/__openerp__.py
l10n_it_fatturapa_in/views/account_view.xml

8.0 IMP Add xml supplier in search xml

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/views/company_view.xml

Fix https://github.com/OCA/l10n-italy/issues/1037

[FIX] l10n_it_fatturapa_pec: https://github.com/OCA/l10n-italy/issues/1037

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/views/account_view.xml

v8: https://github.com/OCA/l10n-italy/pull/1034

10.0 IMP Add xml supplier in search xml

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

From https://github.com/OCA/l10n-italy/pull/975

[12.0] IMP l10n_it_fatturapa_in using supplier payment term to compute due date

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

From https://github.com/OCA/l10n-italy/pull/975

[11.0] IMP l10n_it_fatturapa_in using supplier payment term to compute due date

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/wizard/ddt_from_picking.py

Add the carrier_id in ddt_from_picking

Fix #1043 [10.0] l10n_it_ddt, corriere mancante

---

l10n_it_fiscalcode/__manifest__.py
l10n_it_fiscalcode/view/fiscalcode_view.xml

This PR simply add fiscalcode to partner search view.

[12.0][IMP][l10n_it_fiscalcode] Add fiscalcode in partner search view

---

l10n_it_fiscalcode/__manifest__.py
l10n_it_fiscalcode/view/fiscalcode_view.xml

[11.0][IMP][l10n_it_fiscalcode] Add fiscalcode in partner search view

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Vedi https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

ADD github default template for issues and PRs

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[8.0] add ability to customize codicetipo

---

l10n_it_fatturapa_in/__openerp__.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR04.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

while importing lines with price 0 and discount 0
See test
backport di #1022 (vedi per dettagli)
--

FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

Add the possibility for module extension to export invoice having multiple discounts in a line

[10.0][IMP][l10n_it_fatturapa_out] Hook for extension to permit to export multiple discounts

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/wizard/ddt_from_picking.py

Fix #1043 [11.0] l10n_it_ddt, corriere mancante

---

l10n_it_fatturapa_out/README.rst
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/readme/CONFIGURE.rst
l10n_it_fatturapa_out/static/description/index.html

Descrizione del problema o della funzionalità: fix: #1113 #819 (incompleta per #819 (comment))
--

[11.0] fix version and readme

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

This PR is for the v12 see #829
--

[12.0][IMP][l10n_it_fatturapa_out] Hook for extension to permit to export multiple discounts

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Fix https://github.com/OCA/l10n-italy/issues/1129
--

[10.0][FIX] l10n_it_fatturapa_in: IstitutoFinanziario and BIC are not mandatory in XML

---

l10n_it_fatturapa_out/README.rst
l10n_it_fatturapa_out/__openerp__.py
l10n_it_fatturapa_out/readme/CONFIGURE.rst
l10n_it_fatturapa_out/static/description/index.html

Descrizione del problema o della funzionalità: fix: #1113 #819 (incompleta per #819 (comment))
--

[8.0] fix version and readme

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/wizard/ddt_from_picking.py

Fixes https://github.com/OCA/l10n-italy/issues/1043
--

[12.0] Fix #1043 l10n_it_ddt, corriere mancante (#1044)

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/data/fatturapa_data.xml
l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
l10n_it_fatturapa/models/company.py
l10n_it_fatturapa/views/company_view.xml
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/models/attachment.py
l10n_it_fatturapa_out/tests/fatturapa_common.py
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py
l10n_it_fatturapa_out_triple_discount/tests/test_fatturapa_triple_discount.py
l10n_it_fatturapa_pec/tests/test_e_invoice_response.py

Otherwise we could handle 99999 invoices only.
While (26 * 26 * 10) ^ 5 = 1,411670957×10¹⁹ are possibile

[10.0] REF l10n_it_fatturapa_out using an alphanumeric sequence for file name

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Reverting part of https://github.com/OCA/l10n-italy/pull/703
v11: https://github.com/OCA/l10n-italy/pull/1011
v12: https://github.com/OCA/l10n-italy/pull/1010

[10.0] Restore DatiCassaPrevidenziale handling: when present, add it as invoice line

---

l10n_it_corrispettivi/__manifest__.py
l10n_it_corrispettivi/models/account.py

Fix https://github.com/OCA/l10n-italy/issues/1156
--

[10.0][FIX] l10n_it_corrispettivi: Find fiscal positions without company

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/data/IT05979361218_011.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Fixes https://github.com/OCA/l10n-italy/issues/1067
--

[12.0][IMP][l10n_it_fatturapa_in] Format Italian VAT ID to always have 11 chars

---

l10n_it_corrispettivi/__init__.py
l10n_it_corrispettivi/__manifest__.py
l10n_it_corrispettivi/wizards/__init__.py
l10n_it_corrispettivi/wizards/account_invoice_refund.py

Fix https://github.com/OCA/l10n-italy/issues/1158
--

[10.0][IMP] l10n_it_corrispettivi: Show the corrispettivi tree view as a result of refund wizard

---

l10n_it_reverse_charge/__manifest__.py
l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/tests/test_rc.py

Fix https://github.com/OCA/l10n-italy/issues/1154
--

[10.0][FIX] l10n_it_reverse_charge: Check RC flag in lines of brand new vendor bill refund

---

l10n_it_website_sale_fatturapa/__manifest__.py
l10n_it_website_sale_fiscalcode/__manifest__.py

Quando le loro dipendenze sono installate, non ha senso lasciarli disinstallati

[12.0] auto_install e-commerce modules

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/mail_thread.py

[FIX] valid other countries intermediary filename

---

l10n_it_fatturapa_pec/__openerp__.py
l10n_it_fatturapa_pec/models/mail_thread.py

Descrizione del problema o della funzionalità: alcune e-fatture non sono recepite
Comportamento attuale prima di questa PR: le fatture ricevute da intermediari esteri non sono recepite
Comportamento desiderato dopo questa PR: le fatture vengono recepite
--

[8.0][FIX] valid other countries intermediary filename

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/mail_thread.py

https://github.com/OCA/l10n-italy/issues/922

[12.0] [FIX] parse e-invoice filename from intermediary from other countries (#1133)

---

l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/partner.py

https://github.com/OCA/l10n-italy/issues/1131

[FIX] l10n_it_fatturapa: Add cross check pec_destinatario and codice_destinatario

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/mail_thread.py

https://github.com/OCA/l10n-italy/issues/1189
--

[10.0] Fix FATTURAPA_IN_REGEX to allow signed incoming invoices

---

l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/mail_thread.py

https://github.com/OCA/l10n-italy/issues/1189
--

[12.0] Fix FATTURAPA_IN_REGEX to allow signed incoming invoices

---

l10n_it_corrispettivi/__init__.py
l10n_it_corrispettivi/__manifest__.py
l10n_it_corrispettivi/wizards/__init__.py
l10n_it_corrispettivi/wizards/account_invoice_refund.py

https://github.com/OCA/l10n-italy/issues/1158

[12.0] [IMP] l10n_it_corrispettivi: Show the corrispettivi tree view as a result of refund wizard

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/views/account_view.xml

Close https://github.com/OCA/l10n-italy/issues/1193 per v10
--

[10.0][IMP] l10n_it_fatturapa_in: Add total in attachment's tree view

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Reverting part of https://github.com/OCA/l10n-italy/pull/703

[11.0] Restore DatiCassaPrevidenziale handling: when present, add it as invoice line

---

l10n_it_fatturapa/README.rst
l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
l10n_it_fatturapa/models/company.py
l10n_it_fatturapa/models/ir_attachment.py
l10n_it_fatturapa/readme/CONFIGURE.rst
l10n_it_fatturapa/readme/CONTRIBUTORS.rst
l10n_it_fatturapa/views/company_view.xml

This PR improve the e-invoice preview format by supporting multiple formats accessible by a dedicated selection in the fatturapa company options. 
It also add the AssoSoftware preview format which is FAR better and readable compared to the one provided by ADE!

[10.0][l10n_it_fatturapa] Add support to multiple invoice preview formats

---

account_vat_period_end_statement/__manifest__.py
account_vat_period_end_statement/views/report_vatperiodendstatement.xml

[12.0] IMP account_vat_period_end_statement report: do not print rows with zero values

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/data/ddt_data.xml
l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_fatturapa_out_ddt/__manifest__.py
l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml

[10.0][FIX] missing translate boolean and order ddt ported from 8.0

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

Close https://github.com/OCA/l10n-italy/issues/1204 for 10.0
--

[10.0][FIX] l10n_it_fatturapa_out: DatiRiepilogo is mandatory but tax_line_ids is not required

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/views/report_ddt.xml

Fix https://github.com/OCA/l10n-italy/issues/1236
--

[FIX] l10n_it_ddt: fix https://github.com/OCA/l10n-italy/issues/1236

---

l10n_it_fatturapa_out/README.rst
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/readme/CONFIGURE.rst
l10n_it_fatturapa_out/static/description/index.html
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

IMP l10n_it_fatturapa allowing to specify 'ODOO' code prefix in XML, fixed version and readme

---

l10n_it_invoices_data_communication/__manifest__.py
l10n_it_invoices_data_communication/models/communication.py

Close https://github.com/OCA/l10n-italy/issues/1241 for v10
--

[10.0][FIX] l10n_it_invoices_data_communication: cessionario cedente

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

Close https://github.com/OCA/l10n-italy/issues/1245 for v10
--

[10.0][FIX] l10n_it_fatturapa_out: DettaglioPagamento creation

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/account.py
l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/account_view.xml
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Close https://github.com/OCA/l10n-italy/issues/1208 for v10
--

[10.0][IMP] l10n_it_fatturapa_in: Overwrite supplier invoice data when importing

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/models/stock.py
l10n_it_ddt/views/stock_picking.xml

l10n_it_ddt: add TD Info to incoming picking

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1245
--

[12.0] [FIX] l10n_it_fatturapa_out: DettaglioPagamento creation (#1246)

---

l10n_it_fatturapa/README.rst
l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
l10n_it_fatturapa/models/company.py
l10n_it_fatturapa/models/ir_attachment.py
l10n_it_fatturapa/readme/CONFIGURE.rst
l10n_it_fatturapa/readme/CONTRIBUTORS.rst
l10n_it_fatturapa/views/company_view.xml

This PR improve the e-invoice preview format by supporting multiple formats accessible by a dedicated selection in the fatturapa company options.
It also add the AssoSoftware preview format which is FAR better and readable compared to the one provided by ADE!
See #1036 for v10.0

[12.0][l10n_it_fatturapa] Add support to multiple invoice preview formats

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
l10n_it_rea/__manifest__.py
l10n_it_rea/models/res_partner.py

This should fix bug OCA#1029 as proposed in the issue's opening comment.

[11.0] [FIX] l10n_it_fatturapa_in: OCA#1029 (avoid unique REA Code constraint)

---

setup/l10n_it_fatturapa/setup.py

Forward port di https://github.com/OCA/l10n-italy/pull/1180
--

[12.0][IMP] add pyxb version dependency

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Reverting part of https://github.com/OCA/l10n-italy/pull/703

[12.0] Restore DatiCassaPrevidenziale handling: when present, add it as invoice line

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
l10n_it_fatturapa_out_wt/models/withholding_tax.py

Close https://github.com/OCA/l10n-italy/issues/1310 per v10
--

[10.0][IMP] l10n_it_fatturapa_in: When linking an e-invoice to an invoice, set reference and invoice date in the invoice if empty

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

This should fix bug OCA#1029 as proposed in the issue's opening comment.

[10.0] [FIX] l10n_it_fatturapa_in: OCA#1029 (avoid unique REA Code constraint)

---

l10n_it_ddt/README.rst
l10n_it_ddt/__manifest__.py
l10n_it_ddt/models/__init__.py
l10n_it_ddt/models/partner.py
l10n_it_ddt/models/product.py
l10n_it_ddt/models/sale.py
l10n_it_ddt/models/stock.py
l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py
l10n_it_ddt/views/partner.xml
l10n_it_ddt/views/product.xml
l10n_it_ddt/views/sale.xml
l10n_it_ddt/wizard/ddt_from_picking.py

https://github.com/OCA/l10n-italy/issues/1291
--

[10][l10n_it_ddt]  fatturazione servizi da DDT

---

l10n_it_withholding_tax/__manifest__.py
l10n_it_withholding_tax/models/account.py

[12.0] Fix withholding tax duplication

---

l10n_it_account/reports/account_reports_view.xml

Vedi https://github.com/OCA/l10n-italy/issues/1339
--

[12.0] fix number page in footer when print report with more page

---

.travis.yml

updating travis configuration
--

FIX Assertion failed on job for postgresql@9.2-main.service.

---

.travis.yml

update travis to fix postgres build error

---

l10n_it_fatturapa/bindings/README.md
l10n_it_fatturapa/bindings/_ds.py
l10n_it_fatturapa/bindings/binding.py
l10n_it_fatturapa/bindings/bindings.diff
l10n_it_fatturapa/bindings/fatturapa.py
l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_pec/models/fetchmail.py
l10n_it_fatturapa_pec/tests/test_e_invoice_response.py
l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
l10n_it_invoices_data_communication/README.rst
l10n_it_invoices_data_communication/readme/ROADMAP.rst
l10n_it_invoices_data_communication/static/description/index.html
l10n_it_withholding_tax/models/withholding_tax.py
l10n_it_withholding_tax/tests/__init__.py
l10n_it_withholding_tax/tests/test_withholding_tax.py

Rendere lint, e quindi travis, verde per il branch 10.0
--

[10.0] make lint green

---

.travis.yml

updating travis configuration
--

[8.0][FIX] Assertion failed on job for postgresql@9.2-main.service.

---

l10n_it_fiscal_document_type/models/fiscal_document_type.py

Closing #1386 for v11.
Cherry-pick di https://github.com/OCA/l10n-italy/pull/1387.
--

[11.0][IMP] l10n_it_fiscal_document_type: nome e codice obbligatori

---

l10n_it_withholding_tax/models/account.py

[10.0][fix] withholding tax duplication

---

l10n_it_fiscal_document_type/models/fiscal_document_type.py

Closing #1386 for v8.
Cherry-pick di #1387.
--

[8.0][IMP] l10n_it_fiscal_document_type: nome e codice obbligatori

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/models/attachment.py
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py

[10.0][IMP] l10n_it_fatturapa_* - Nome file univoco

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

Vedi https://github.com/OCA/l10n-italy/issues/1438
Le righe rimosse sono già presenti sotto
--

[12.0] FIX l10n_it_fatturapa_out: remove duplicate code

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

Closing https://github.com/OCA/l10n-italy/issues/1438 per v11
--

[11.0][FIX] l10n_it_fatturapa_out: remove duplicate code

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py

Vedi https://github.com/OCA/l10n-italy/issues/1446
--

[12.0] FIX l10n_it_ddt: ddt.invoicing wizard

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Vedi https://github.com/OCA/l10n-italy/issues/1435
--

[11.0][l10n_fatturapa_in] [fix] get fiscal_position_id from partner if set

---

l10n_it_fatturapa_in/tests/data/IT01234567890_FPR05.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Vedi https://github.com/OCA/l10n-italy/issues/1447
--

[12.0] FIX l10n_it_fatturapa_in when importing XML with 100% discount. See test case

---

l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/tests/test_rc.py

Vedi https://github.com/OCA/l10n-italy/issues/1450
--

[12.0] IMP l10n_it_reverse_charge: write supplier invoice data in self invoice comments

---

l10n_it_website_portal_fatturapa/views/l10n_it_website_portal_fatturapa_templates.xml

Closing https://github.com/OCA/l10n-italy/issues/1420 per v10
--

[10.0][FIX] l10n_it_website_portal_fatturapa: Fix electronic invoice label

---

l10n_it_withholding_tax/models/withholding_tax.py

Issue di riferimento https://github.com/OCA/l10n-italy/issues/1327
--

[10.0][FIX] l10n_it_withholding_tax: Added condition upon 'date_end' column in where clause for _get_rate method

---

account_invoice_report_ddt_group/models/account_invoice.py

[12.0] FIX account_invoice_report_ddt_group ValueError: Expected singleton

---

account_invoice_report_ddt_group/models/account_invoice.py

https://github.com/OCA/l10n-italy/issues/1477
--

[12.0] FIX account_invoice_report_ddt_group when invoicing services

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_out/models/attachment.py
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py

Closing https://github.com/OCA/l10n-italy/issues/1382 per v12
--

[12.0] l10n_it_fatturapa_* - Nome file univoco

---

l10n_it_fatturapa_in/tests/data/IT01234567890_FPR05.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Closing https://github.com/OCA/l10n-italy/issues/1447 per v10
--

[10.0][FIX] l10n_it_fatturapa_in: when importing XML with 100% discount

---

l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/tests/test_rc.py

[11.0][IMP] l10n_it_reverse_charge: write supplier invoice data in self invoice comments

---

l10n_it_fatturapa_in/models/attachment.py

[12.0] [FIX] e-invoice translation source terms

---

l10n_it_fiscalcode_crm/__init__.py
l10n_it_fiscalcode_crm/__manifest__.py
l10n_it_fiscalcode_crm/models/__init__.py
l10n_it_fiscalcode_crm/models/crm_lead.py
l10n_it_fiscalcode_crm/readme/CONTRIBUTORS.rst
l10n_it_fiscalcode_crm/readme/DESCRIPTION.rst
l10n_it_fiscalcode_crm/tests/__init__.py
l10n_it_fiscalcode_crm/tests/test_lead.py
l10n_it_fiscalcode_crm/views/crm_lead.xml

ADD l10n_it_fiscalcode_crm: This module extends the functionality of CRM leads allowing to set the fiscal code

---

l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/tests/test_rc.py

[10.0][IMP] l10n_it_reverse_charge: write supplier invoice data in self invoice comments

---

l10n_it_withholding_tax/models/withholding_tax.py

Vedi https://github.com/OCA/l10n-italy/issues/1327
--

[12.0] [FIX] l10n_it_withholding_tax: Added condition upon 'date_end' column in where clause for _get_rate method

---

l10n_it_reverse_charge/README.rst
l10n_it_reverse_charge/readme/CONFIGURE.rst
l10n_it_reverse_charge/static/description/index.html

Le immagini del README non si vedono
Le immagini del README si vedono
--

[12.0] FIX l10n_it_reverse_charge README

---

l10n_it_withholding_tax/models/account.py

After a1628210121346f6f4f5d9e10411e58eeebdf245
See https://github.com/OCA/l10n-italy/issues/1486
--

[12.0] FIX l10n_it_withholding_tax _onchange_invoice_line_wt_ids: always set withholding_tax True

---

l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/security/rules.xml
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/security/rules.xml
l10n_it_fatturapa_pec/README.rst
l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/models/__init__.py
l10n_it_fatturapa_pec/models/company.py
l10n_it_fatturapa_pec/models/mail_thread.py
l10n_it_fatturapa_pec/readme/CONFIGURE.rst
l10n_it_fatturapa_pec/static/description/index.html
l10n_it_fatturapa_pec/views/company_view.xml
l10n_it_sdi_channel/models/sdi.py

Allineata alle ultime modifiche della v12.0. Vedi #877 
--

12.0 l10n it fatturapa pec multicompany

---

l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/tests/test_rc.py

Vedi https://github.com/OCA/l10n-italy/issues/1491
--

[10.0] FIX l10n_it_reverse_charge when supplier RC tax is 0

---

l10n_it_fatturapa_in_rc/tests/test_fatturapa_in_rc.py
l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1501
Vedi anche test case aggiunto
--

[12.0] FIX l10n_it_fatturapa_in_rc when importing e-invoice with Minimum detail level

---

l10n_it_location_nuts/wizard/nuts_import.py

FIX missing sud sardegna

---

l10n_it_location_nuts/wizard/nuts_import.py

Descrizione del problema o della funzionalità: mancanza di una provincia
--

[FIX] missing sud sardegna

---

l10n_it_fatturapa_in/tests/data/IT01234567890_FPR05.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Closing https://github.com/OCA/l10n-italy/issues/1447 per v8
--

[8.0][FIX] l10n_it_fatturapa_in: when importing XML with 100% discount

---

l10n_it_fatturapa_out/models/attachment.py

[8.0][FIX] double attach in fatturapa out xml

---

l10n_it_fatturapa_in/tests/data/IT01234567890_FPR05.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Closing https://github.com/OCA/l10n-italy/issues/1447 for v11
--

[11.0][FIX] l10n_it_fatturapa_in: when importing XML with 100% discount

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/data/l10n_it_fatturapa_out_data.xml
l10n_it_fatturapa_out/tests/data/CHE114993395IVA_00007.xml
l10n_it_fatturapa_out/tests/data/IT03297040366_00005.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00001.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00002.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00003.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00004.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00006.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00008.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00009.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00006.xml
l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml

Descrizione del problema o della funzionalità: vedi issue https://github.com/OCA/l10n-italy/issues/1340
questa pr sostituisce la https://github.com/OCA/l10n-italy/pull/1353 
--

11.0 fix l10n it decimal precision on fatturapa

---

l10n_it_fatturapa_out/__openerp__.py
l10n_it_fatturapa_out/data/l10n_it_fatturapa_out_data.xml
l10n_it_fatturapa_out/tests/data/CHE114993395IVA_00007.xml
l10n_it_fatturapa_out/tests/data/IT03297040366_00005.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00001.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00002.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00003.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00004.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00006.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00008.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00009.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00006.xml
l10n_it_fatturapa_out_ddt/tests/data/IT06363391001_00007.xml
l10n_it_fatturapa_out_triple_discount/tests/data/IT06363391001_00001.xml

Descrizione del problema o della funzionalità: #1340 descritto nell aissue
--

8.0 [FIX] aggiunta decimal precision su prezzo unitario

---

l10n_it_fatturapa_in_rc/__manifest__.py

Descrizione del problema o della funzionalità: errata impostazione variabile auto_install
--

[FIX] autoinstall

---

setup/l10n_it_fatturapa/setup.py

[IMP] Add pyxb version dependency

---

l10n_it_fatturapa/views/company_view.xml

as they are not expected
Vedi https://github.com/OCA/l10n-italy/issues/1525
--

[12.0] IMP l10n_it_fatturapa prevent user to create fatturapa.fiscal_position records

---

l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1536
--

[12.0] IMP l10n_it_fatturapa_in: use last due date for invoice due date, if supplier payment term is not set

---

l10n_it_reverse_charge/models/account_invoice.py

[8.0][IMP] l10n_it_reverse_charge: write supplier invoice data in self invoice comments

---

l10n_it_corrispettivi/README.rst
l10n_it_corrispettivi/__manifest__.py
l10n_it_corrispettivi/views/account_report.xml

Descrizione del problema o della funzionalità: fix https://github.com/OCA/l10n-italy/issues/1555, superseed https://github.com/OCA/l10n-italy/pull/1580
--

[12.0][FIX] l10n_it_corrispettivi, fix account report

---

l10n_it_fatturapa/data/fatturapa_data.xml

Vedi https://github.com/OCA/l10n-italy/issues/1572
--

[12.0] FIX e-invoice fiscal position: update law reference

---

l10n_it_fatturapa_out_triple_discount/tests/__init__.py

Vedi https://github.com/OCA/l10n-italy/issues/1588
--

[12.0] l10n_it_fatturapa_out_triple_discount: disable tests because unstable

---

l10n_it_central_journal/views/report_account_central_journal.xml
l10n_it_central_journal/wizard/print_giornale.py

[IMP] 12.0 - Order data on central journal and print line name or partner name

---

account_vat_period_end_statement/reports.xml
account_vat_period_end_statement/views/config.xml
account_vat_period_end_statement/views/report_vatperiodendstatement.xml
l10n_it_ateco/view/ateco_view.xml
l10n_it_base_crm/crm/crm_view.xml
l10n_it_bill_of_entry/account_invoice_view.xml
l10n_it_bill_of_entry/company_view.xml
l10n_it_central_journal/views/account_view.xml
l10n_it_corrispettivi/installer_view.xml
l10n_it_corrispettivi/partner_data.xml
l10n_it_fatturapa_in/tests/data/IT03638121008_X11111.xml
l10n_it_fatturapa_in/tests/data/IT05979361218_005.xml
l10n_it_fatturapa_in/tests/data/IT05979361218_006.XML
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml
l10n_it_fiscalcode/view/fiscalcode_view.xml
l10n_it_fiscalcode/wizard/compute_fc_view.xml
l10n_it_regions/views/region_view.xml
l10n_it_ricevute_bancarie/views/configuration_view.xml
l10n_it_split_payment/views/account_view.xml
l10n_it_split_payment/views/config_view.xml
l10n_it_withholding_tax_payment/views/withholding_tax.xml

[8.0] xml files: 4 spaces instead tabs

---

l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1594
--

[12.0] Aggiunta possibilità di scelta della data di default in cui registrare le fatture di acquisto generate da xml

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Closing https://github.com/OCA/l10n-italy/issues/1435 for v8
--

[8.0][FIX] get fiscal_position_id from partner if set

---

l10n_it_fatturapa_in/models/account.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR08.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py

Vedi https://github.com/OCA/l10n-italy/issues/1625
--

[12.0] IMP l10n_it_fatturapa_in when XML contains DatiRitenuta but suppliers did not set Ritenuta for any line

---

l10n_it_withholding_tax/models/account.py
l10n_it_withholding_tax/models/voucher.py
l10n_it_withholding_tax/models/withholding_tax.py

Questa PR ha l'obiettivo di correggere gli errori rilevati da pylint nella PR #1544 relativi al modulo l10n_it_withholding_tax.
I controlli pylint della PR #1544 rilevano errori bloccanti
I controlli pylint della PR #1544 vengono superati
--

[8.0][FIX] l10n_it_withholding_tax: _check_date search by ORM + Pylint fixes

---

l10n_it_fatturapa_in/models/company.py
l10n_it_fatturapa_in/views/company_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1594
--

[10.0] Aggiunta possibilità di scelta della data di default in cui registrare le fatture di acquisto generate da xml

---

account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/tests/test_vat_statement.py
account_vat_period_end_statement/views/account_view.xml
l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py

https://github.com/OCA/l10n-italy/issues/1646
+
https://github.com/OCA/l10n-italy/issues/1649
--

[12.0] gestione acconto in liquidazione IVA + VP14 non compilato per trimestrali nel 4° trimestre

---

l10n_it_account/reports/account_reports_view.xml
l10n_it_vat_registries/models/vat_registry.py
l10n_it_vat_registries/report/report_registro_iva.xml
l10n_it_vat_registries/wizard/print_registro_iva.py
l10n_it_vat_registries/wizard/print_registro_iva.xml
l10n_it_vat_registries_cash_basis/wizard/print_registro_iva.py

Prima di questa PR non avevo la possibilità di scegliere l'anno nella stampa registro iva
Dopo di questa PR ho la possibilità di scegliere l'anno nella stampa registro iva
--

[IMP] 10.0 - Possibilità di modificare numero di pagina nel footer registro iva in base all'anno indicato nel campo year_footer

---

l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py
l10n_it_vat_statement_communication/views/comunicazione_liquidazione.xml
l10n_it_vat_statement_communication/wizard/export_file.py

https://github.com/OCA/l10n-italy/issues/1646 + https://github.com/OCA/l10n-italy/issues/1659
--

[12.0] FIX l10n_it_vat_statement_communication adding "Down payment computation method" to be set when "Down payment due" is set

---

l10n_it_central_journal/views/report_account_central_journal.xml
l10n_it_central_journal/wizard/print_giornale.py

See https://github.com/OCA/l10n-italy/issues/1550
--

[IMP] 11.0 - Order data on central journal and print line name or partner name

---

account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/views/account_view.xml

https://github.com/OCA/l10n-italy/issues/1653
--

[12.0] IMP account_vat_period_end_statement allowing to create an annual prospect, without accounting entries

---

account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/views/account_view.xml
account_vat_period_end_statement/views/report_vatperiodendstatement.xml

Closing https://github.com/OCA/l10n-italy/issues/1665 for `v10`.
--

[10.0] [IMP] account_vat_period_end_statement: allow to print in the report footer a year other than the current year

---

account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/views/account_view.xml

https://github.com/OCA/l10n-italy/issues/1653
--

[12.0] Annual prospect of VAT statement: do not compute previous credits. Add annual field to list and search view

---

.travis.yml

Attempt to workaround sqlalchemy installation issue, by not installing it.
--

[10.0] install dependencies with pip

---

l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py

[10.0] FIX attach state on EC01 email text result

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1691
--

[12.0] IMP l10n_it_fatturapa_out making your company messages more clear

---

.travis.yml

https://github.com/OCA/l10n-italy/issues/1700
--

[10.0] IMP travis installation using dependencies from addon manifests

---

l10n_it_fatturapa_pec/models/mail_thread.py

[10.0][FIX] l10n_it_fatturapa_pec: Find fatturapa_attachment_out res by signed attach_name

---

.travis.yml

https://github.com/OCA/l10n-italy/issues/1700
--

[12.0] IMP travis installation using dependencies from addon manifests

---

l10n_it_central_journal/__manifest__.py
l10n_it_central_journal/views/report_account_central_journal.xml

Fix https://github.com/OCA/l10n-italy/issues/1651 per v10.
--

[10.0][FIX] l10n_it_central_journal: Break long words in fields that can contain them

---

l10n_it_intrastat_statement/models/intrastat_statement.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py

[12.0][FIX] Dichiarazione Intrastat: Arrotondamenti a 1 in caso di valore inferiore a zero (AMMONT. EURO, VALORE STATIST, MASSA NETTA, UNITA' SUPPL)

---

l10n_it_sdi_channel/views/sdi_view.xml

https://github.com/OCA/l10n-italy/issues/1705
--

[12.0] IMP l10n_it_sdi_channel hiding "web server" fields ad attrs is not applicable to tree view

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/views/report_ddt.xml
l10n_it_ddt/views/stock_picking_package_preparation.xml

https://github.com/OCA/l10n-italy/issues/1706
--

[12.0] IMP l10n_it_ddt allowing to show lot deadline in DDT report

---

l10n_it_vat_registries/report/report_registro_iva.xml

https://github.com/OCA/l10n-italy/issues/1713
--

[12.0] IMP l10n_it_vat_registries printing VAT reg name if present

---

l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/tests/test_rc.py

https://github.com/OCA/l10n-italy/issues/1716
--

[12.0] FIX l10n_it_reverse_charge when supplier invoice total is 0

---

l10n_it_intrastat_statement/models/intrastat_statement.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py

https://github.com/OCA/l10n-italy/issues/1729
https://github.com/OCA/l10n-italy/issues/1730
--

12.0 7047 fix intrastat

---

l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py

https://github.com/OCA/l10n-italy/issues/1738
--

[12.0] FIX l10n_it_vat_statement_communication: interessi_dovuti amount must come from interests_debit_vat_amount

---

l10n_it_abicab/views/abicab_view.xml

[12.0] [IMP]  l10n_it_abicab - add search view

---

l10n_it_account_stamp/models/invoice.py

Vedi https://github.com/OCA/l10n-italy/issues/1727
--

[12.0] Fix l10n_it_account_stamp: tax_stamp computation.

---

l10n_it_vat_registries/models/vat_registry.py

https://github.com/OCA/l10n-italy/issues/1355
--

[12.0]  FIX l10n_it_vat_registries: Negative tax line in supplier invoice, must be negative in vat register line

---

l10n_it_fatturapa/models/account.py
l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/migrations/12.0.1.15.0/post-migration.py
l10n_it_fatturapa_in/models/account.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR09.xml
l10n_it_fatturapa_in/tests/fatturapa_common.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1755
--

[12.0] IMP l10n_it_fatturapa_in: alert user when WT data are incoherent

---

fiscal_epos_print/views/point_of_sale.xml

[12.0] IMP fiscal_epos_print POS config view

---

l10n_it_ricevute_bancarie/models/riba.py

Vedi https://github.com/OCA/l10n-italy/issues/1734
--

[12.0][FIX] to not use move name when it is equal to /

---

l10n_it_sdi_channel/views/sdi_view.xml

[12.0][IMP] l10n_it_sdi_channel, add form header

---

l10n_it_ricevute_bancarie/__manifest__.py
l10n_it_ricevute_bancarie/models/riba.py
l10n_it_ricevute_bancarie/views/riba_detail_view.xml

[12.0] Port distinta riba line view from 8.0

---

l10n_it_intrastat/models/account.py

[12.0][FIX]  l10n_it_intrastat: When delete invoice intrastat lines has to be deleted too

---

l10n_it_withholding_tax/views/account.xml

https://github.com/OCA/l10n-italy/issues/1762

[10.0] [IMP] l10n_it_withholding_tax: show amount_net_pay field in invoice_supplier_tree view

---

l10n_it_ricevute_bancarie/models/riba.py

Vedi https://github.com/OCA/l10n-italy/issues/1734
--

[12.0][IMP] add more info in move line created from riba

---

l10n_it_ricevute_bancarie/views/riba_detail_view.xml

Correzione di un piccolo refuso (0 al posto di una O).
--

[12.0][FIX] l10n_it_ricevute_bancarie typo in source string

---

l10n_it_withholding_tax/views/account.xml

https://github.com/OCA/l10n-italy/issues/1762
--

[12.0] l10n_it_withholding_tax: show amount_net_pay field in invoice_supplier_tree view

---

fiscal_epos_print/static/src/js/epson_epos_print.js

https://github.com/OCA/l10n-italy/issues/1777
--

[12.0] FIX fiscal_epos_print when printing receipts with 1 digit day

---

l10n_it_fatturapa_pec/models/mail_thread.py

(usually empty here and less significant anyway)
--

[12.0] IMP l10n_it_fatturapa_pec notifying errors using email subject instead of message-id

---

l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py

Il test che controlla il superamento del plafond non mi pare corretto: passava solo perché l'imponibile dell'unica imposta nella nota di credito non veniva aggiornato.
Mi sono accorto di tutto ciò durante il backporting in v10 del modulo (https://github.com/OCA/l10n-italy/pull/1811), dove l'imponibile invece viene correttamente aggiornato.
Nel test, la validazione della nota di credito non solleva eccezione.
Nel test, la validazione della nota di credito solleva eccezione.
--

[12.0][FIX] l10n_it_dichiarazione_intento: test per nota di credito che supera plafond

---

l10n_it_fatturapa_pec/models/mail_thread.py

https://github.com/OCA/l10n-italy/issues/1668
--

[12.0] [FIX] Find fatturapa_attachment_out res by signed attach_name

---

l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py

[12.0] [FIX] attach state on EC01 email text result

---

l10n_it_ddt/__manifest__.py
l10n_it_ddt/migrations/12.0.1.7.1/pre-migrate.py
l10n_it_ddt/models/partner.py
l10n_it_ddt/models/sale.py
l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py
l10n_it_ddt/views/report_ddt.xml
l10n_it_ddt/views/sale.xml
l10n_it_ddt/views/stock_picking_package_preparation.xml
l10n_it_ddt/wizard/ddt_from_picking.py

Closing https://github.com/OCA/l10n-italy/issues/1843 for `v12.0`.

[FIX] l10n_it_ddt: ddt_show_price did not spread in TD

---

l10n_it_ddt/models/sale.py
l10n_it_ddt/views/sale.xml

Closing https://github.com/OCA/l10n-italy/issues/1845 for `v10.0`

[IMP] l10n_it_ddt: show number of TDs linked to the sale order

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py
l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/account.py
l10n_it_fatturapa/views/account_view.xml
l10n_it_fatturapa/views/related_document_type_views.xml
l10n_it_fatturapa_sale/__init__.py
l10n_it_fatturapa_sale/__manifest__.py
l10n_it_fatturapa_sale/i18n/it.po
l10n_it_fatturapa_sale/models/__init__.py
l10n_it_fatturapa_sale/models/account_invoice.py
l10n_it_fatturapa_sale/models/account_invoice_line.py
l10n_it_fatturapa_sale/models/related_document.py
l10n_it_fatturapa_sale/models/sale_order.py
l10n_it_fatturapa_sale/models/sale_order_line.py
l10n_it_fatturapa_sale/readme/DESCRIPTION.rst
l10n_it_fatturapa_sale/tests/__init__.py
l10n_it_fatturapa_sale/tests/test_fatturapa_sale.py
l10n_it_fatturapa_sale/views/related_document_type_views.xml
l10n_it_fatturapa_sale/views/sale_order_line_views.xml
l10n_it_fatturapa_sale/views/sale_order_views.xml
setup/l10n_it_fatturapa_sale/odoo/addons/l10n_it_fatturapa_sale
setup/l10n_it_fatturapa_sale/setup.py

Aggiungere i campi **Admin. Ref.** e **Documenti correlati** nell'ordine di vendita, da propagare alla fattura in fase di creazione della stessa.
--

[12.0][ADD] l10n_it_fatturapa_sale

---

l10n_it_account_tax_kind/data/account.tax.kind.csv
l10n_it_account_tax_kind/model/account_tax_kind.py
l10n_it_fatturapa/models/account.py

[12.0][IMP] l10n it account tax kind fatturapa 1.6

---

l10n_it_fiscal_document_type/data/fiscal.document.type.csv
l10n_it_fiscal_document_type/models/fiscal_document_type.py

[12.0][IMP] aggiunti fiscal document types fatturapa 1.6

---

l10n_it_causali_pagamento/__manifest__.py
l10n_it_causali_pagamento/data/causali_pagamento_data.xml
l10n_it_causali_pagamento/migrations/12.0.1.1.0/post-migrate.py
l10n_it_causali_pagamento/readme/CONTRIBUTORS.rst
l10n_it_causali_pagamento/tests/test_causali.py

[IMP] l10n_it_causali_pagamento: modify casuale.pagamento records according to e-invoicing specs 1.6

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_out_triple_discount/wizards/wizard_export_fatturapa.py

[12.0][IMP] l10n_it_fatturapa_out and l10n_it_fatturapa_out_triple_discount: modifica del type di Importo in ScontoMaggiorazioneType

---

l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00014.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00016.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00017.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00018.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00019.xml
l10n_it_fatturapa_out_wt/tests/test_fatturapa_wt.py
l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py
l10n_it_withholding_tax/i18n/it.po
l10n_it_withholding_tax/i18n/l10n_it_withholding_tax.pot
l10n_it_withholding_tax/models/withholding_tax.py
l10n_it_withholding_tax/views/withholding_tax.xml
l10n_it_withholding_tax_causali/views/withholding_tax.xml

12.0 nuovi dati ritenuta fe

---

l10n_it_intrastat/__manifest__.py
l10n_it_intrastat/models/account.py
l10n_it_intrastat_statement/__manifest__.py
l10n_it_intrastat_statement/models/intrastat_statement.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/models/intrastat_statement_section.py
l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
l10n_it_intrastat_statement/tests/test_intrastat_statement.py

Closing #1870 per v10.
Cherry-pick di https://github.com/OCA/l10n-italy/pull/1751.
--

[10.0][FIX] l10n_it_intrastat_statement: Different statement produced for month/quarter, refactoring

---

l10n_it_fatturapa_pec/tests/test_e_invoice_response.py

Closing https://github.com/OCA/l10n-italy/issues/1882
--

[12.0] Eccezione durante l'esecuzione dei test

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1129
--

[12.0] [FIX] l10n_it_fatturapa_in: IstitutoFinanziario and BIC are not mandatory in XML

---

l10n_it_dichiarazione_intento/models/sale.py

[12.0][FIX] sale order is a datetime but dichiarazione d'intento dates are date

---

l10n_it_esigibilita_iva/models/account.py
l10n_it_fatturapa/models/account.py

Use correct english terms, from APPENDIX A -TECHNICAL SPECIFICATIONS

---

l10n_it_invoices_data_communication/models/account_invoice.py

https://github.com/OCA/l10n-italy/issues/1670
--

[12.0] IMP l10n_it_invoices_data_communication handling new RC codes from 1.6 version

---

l10n_it_fiscalcode_sale/__manifest__.py
l10n_it_fiscalcode_sale/i18n/it.po
l10n_it_fiscalcode_sale/readme/CONTRIBUTORS.rst
l10n_it_fiscalcode_sale/readme/DESCRIPTION.rst
l10n_it_fiscalcode_sale/views/sale_order_report.xml
setup/l10n_it_fiscalcode_sale/odoo/addons/l10n_it_fiscalcode_sale
setup/l10n_it_fiscalcode_sale/setup.py

[12.0] ADD l10n_it_fiscalcode_sale: Mostra il codice fiscale del cliente nella stampa del preventivo

---

l10n_it_fatturapa/README.rst
l10n_it_fatturapa/data/FoglioStileAssoSoftware_v1.1.xsl
l10n_it_fatturapa/models/company.py
l10n_it_fatturapa/models/ir_attachment.py
l10n_it_fatturapa/readme/CONFIGURE.rst
l10n_it_fatturapa/readme/CONTRIBUTORS.rst
l10n_it_fatturapa/views/company_view.xml

This PR improve the e-invoice preview format by supporting multiple formats accessible by a dedicated selection in the fatturapa company options.
It also add the AssoSoftware preview format which is FAR better and readable compared to the one provided by ADE!
--

[11.0][l10n_it_fatturapa] Add support to multiple invoice preview formats

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

11.0 fatturapa in: search by VAT and CF

---

l10n_it_reverse_charge/models/account_invoice.py

Questa PR corregge l'errore alla validazione di una fattura fornitore "Le registrazioni non sono dello stesso conto"
Questo problematica c'è sulla 11.
Sulla 12 non c'è.
Ho corretto riportando il metodo presente sulla 12 nella 11.
Quando si valida una fattura fornitore in reverse charge, appare l'errore "Le registrazioni non sono dello stesso conto"
Quando si valida una fattura fornitore in reverse charge, appare l'errore "Le registrazioni non sono dello stesso conto"
La validazione della fattura termina normalmente creando l'autofattura, il giroconto e vengono effettuate le corrette riconciliazioni
--
Confermo di aver firmato il CLA …

[11.0] [FIX][l10n_it_reverse_charge]

---

l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1670
--

[12.0] IMP l10n_it_fatturapa_in_rc: handling new RC codes from 1.6 version

---

l10n_it_vat_registries/models/account_tax_registry.py
l10n_it_vat_registries/models/vat_registry.py
l10n_it_vat_registries/report/report_registro_iva.xml
l10n_it_vat_registries/security/vat_registry_security.xml
l10n_it_vat_registries/views/account_journal_view.xml
l10n_it_vat_registries/views/account_tax_registry_view.xml
l10n_it_vat_registries/views/account_view.xml
l10n_it_vat_registries/wizard/print_registro_iva.py
l10n_it_vat_registries/wizard/print_registro_iva.xml

Refractoring del codice, miglioramento visualizzazione wizard di stampa, aggiunta possibilità di stampare il dettaglio delle imposte con suddivisione giornaliera
https://github.com/OCA/l10n-italy/issues/1609
--

11.0 upd l10n it vat registries

---

l10n_it_fatturapa_out_ddt/__manifest__.py
l10n_it_fatturapa_out_ddt/readme/DESCRIPTION.rst
l10n_it_fatturapa_out_ddt/readme/USAGE.rst
l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa.py

Changed "shipping invoice" in "accompanying invoice" (see #1908)  to avoid mistakes in meaning + other fixes.
--

[12.0] [FIX] l10n_it_fatturapa_out_ddt use of more appropriate source term

---

l10n_it_fiscal_document_type/models/fiscal_document_type.py

https://github.com/OCA/l10n-italy/issues/1893
--

[12.0] IMP l10n_it_fiscal_document_type allowing to search records by code and showing code in relational fields

---

l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
l10n_it_intrastat_statement/report/intrastat_mod1_ter.xml
l10n_it_intrastat_statement/report/report_intrastat_mod1.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml

issue: https://github.com/OCA/l10n-italy/issues/1897
--

[10.0 fix] l10n_it_intrastat_statement: ValueError: External ID not found in the system: web.internal_layout

---

l10n_it_fatturapa_in/models/partner.py
l10n_it_fatturapa_in/tests/data/IT05979361218_ripilogoiva.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/1941
--

[12.0] Aggiunto livello importazione XML fattura elettronica basato sul riepilogo

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/models/__init__.py
l10n_it_fatturapa_out/models/company.py
l10n_it_fatturapa_out/models/partner.py
l10n_it_fatturapa_out/views/account_view.xml
l10n_it_fatturapa_out/views/company_view.xml
l10n_it_fatturapa_out/views/partner_view.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/tests/e_invoice_common.py
l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
l10n_it_fatturapa_pec/views/account.xml
l10n_it_fatturapa_pec/wizard/__init__.py
l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa_view.xml

La PR riorganizza il codice di ```l10n_it_fatturapa_out``` e ```l10n_it_fatturapa_pec``` tenendo conto delle funzionalità presenti nelle PR #1539 #1563
Rif https://github.com/OCA/l10n-italy/issues/1566
--

[IMP][10.0] Ottimizza il metodo di generazione fatture elettroniche

---

l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/models/__init__.py
l10n_it_fatturapa_out/models/company.py
l10n_it_fatturapa_out/models/partner.py
l10n_it_fatturapa_out/tests/fatturapa_common.py
l10n_it_fatturapa_out/views/company_view.xml
l10n_it_fatturapa_out/views/partner_view.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_pec/__manifest__.py
l10n_it_fatturapa_pec/tests/e_invoice_common.py
l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
l10n_it_fatturapa_pec/views/account.xml
l10n_it_fatturapa_pec/wizard/__init__.py
l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_pec/wizard/wizard_export_fatturapa_view.xml

https://github.com/OCA/l10n-italy/issues/1566
--

[12.0] Permettere di rigenerare il file XML per le fatture elettroniche in stato di errore

---

l10n_it_intrastat/__manifest__.py
l10n_it_intrastat/models/account.py
l10n_it_intrastat_statement/__manifest__.py
l10n_it_intrastat_statement/models/intrastat_statement.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/models/intrastat_statement_section.py
l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
l10n_it_intrastat_statement/tests/__init__.py
l10n_it_intrastat_statement/tests/test_intrastat_statement.py

Closing https://github.com/OCA/l10n-italy/issues/1870 per v12
--

[12.0][FIX] l10n_it_intrastat_statement: Different statement produced for month/quarter, refactoring

---

l10n_it_fatturapa_out/models/attachment.py

Update l10n_it_fatturapa_out/models/attachment.py
Co-Authored-By: Simone Rubino <simone.rubino@agilebg.com>
[FIX] invoice atts unlink
https://github.com/OCA/l10n-italy/issues/1412
--

[FIX] double attach in fatturapa out xml

---

l10n_it_ricevute_bancarie/__manifest__.py
l10n_it_ricevute_bancarie/models/riba.py
l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
l10n_it_ricevute_bancarie/tests/riba_common.py
l10n_it_ricevute_bancarie/tests/test_riba.py
l10n_it_ricevute_bancarie/views/riba_detail_view.xml
l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py
l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py

[12.0][IMP] Add cig-cup compatibility for riba

---

l10n_it_fatturapa_pec/readme/CONTRIBUTORS.rst
l10n_it_fatturapa_pec/tests/test_e_invoice_send.py

Fix test_sender_error
@Tecnativa TT26985

[12.0][FIX] l10n_it_fatturapa_pec: Fix test_sender_error

---

l10n_it_account_stamp/__manifest__.py
l10n_it_account_stamp/readme/CONFIGURE.rst
l10n_it_account_stamp/views/product_view.xml

Fix #1978 + small improvements.
--

[12.0] [FIX] show stamp duty parameters in manual mode

---

l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml

[12.0][IMP] ability to link already open vendor invoices from xml received

---

l10n_it_invoices_data_communication/__manifest__.py
l10n_it_invoices_data_communication/data/res_country_data.xml
l10n_it_invoices_data_communication/models/__init__.py
l10n_it_invoices_data_communication/models/res_country.py
l10n_it_invoices_data_communication/views/res_country_view.xml

https://github.com/OCA/l10n-italy/issues/1993
--

[UPD][l10n_it_invoices_data_communication] remove intrastat dependance

---

l10n_it_account/models/__init__.py
l10n_it_account/models/account_group.py
l10n_it_account/models/res_company.py
l10n_it_account/readme/CONTRIBUTORS.rst
l10n_it_account/tests/test_l10n_it_account.py

Fix multi-locations installed
Locked by:
@Tecnativa TT26985

[12.0][IMP] l10n_it_account: Fix multi-locations installed

---

l10n_it_fatturapa/bindings/fatturapa.py
l10n_it_fatturapa_in/README.rst
l10n_it_fatturapa_in/readme/CONTRIBUTORS.rst
l10n_it_fatturapa_in/static/description/index.html
l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20005.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py

[8.0][FIX] l10n_it_fatturapa_in: remove spaces into Email and PECDestinatario tags

---

l10n_it_fatturapa_out_sale/__openerp__.py
l10n_it_fatturapa_out_sale/models/__init__.py
l10n_it_fatturapa_out_sale/models/company.py
l10n_it_fatturapa_out_sale/views/company_view.xml
l10n_it_fatturapa_out_sale/wizard/wizard_export_fatturapa.py

Modifiche per gestione multi-company dei dati ordine di vendita nelle fatture elettroniche.

[8.0][IMP] add ability to put internal reference for sale order in e-invoice

---

l10n_it_fatturapa/bindings/binding.py

[8.0][FIX] l10n_it_fatturapa: binding types from string to decimal

---

l10n_it_fatturapa/bindings/fatturapa.py
l10n_it_fatturapa_in/tests/data/ITBNCMRA80A01D548T_20005.xml

12.0 fix fatturapa Email trailing space in XML import

---

l10n_it_fatturapa_in/views/account_view.xml

https://github.com/OCA/l10n-italy/issues/2028
--

[12.0][IMP] l10n_it_fatturapa_in: invoices_total field in tree view

---

l10n_it_fatturapa_in/views/account_view.xml

[8.0][IMP] l10n_it_fatturapa_in: invoices_total field in tree view

---

l10n_it_rea/__manifest__.py

[14.0] [FIX] l10n_it_rea category string

---

l10n_it_fatturapa_out/readme/CONTRIBUTORS.rst
l10n_it_fatturapa_out/tests/fatturapa_common.py

Fix error tests to copy files
Please @pedrobaeza review it
@Tecnativa TT26985

[12.0][FIX] l10n_it_fatturapa_out: Fix error tests to copy files

---

l10n_it_fatturapa_sale/models/sale_order_line.py

[FIX][12.0] remove space

---

l10n_it_fatturapa_in/models/company.py

[8.0][FIX] l10n_it_fatturapa_in: no 'deprecated' field in v8

---

l10n_it_reverse_charge/models/account_invoice.py

[12.0] [FIX] l10n_it_reverse_charge: remove bank account from self-billed invoice

---

fiscal_epos_print/__manifest__.py
fiscal_epos_print/models/account_journal.py
fiscal_epos_print/models/pos_order.py
fiscal_epos_print/readme/CONTRIBUTORS.rst
fiscal_epos_print/static/lib/fiscalprint/fiscalprint.js
fiscal_epos_print/static/src/js/epson_epos_print.js
fiscal_epos_print/static/src/js/models.js
fiscal_epos_print/static/src/js/popups.js
fiscal_epos_print/static/src/js/pos_order_mgmt.js
fiscal_epos_print/static/src/js/screens.js
fiscal_epos_print/static/src/xml/lottery.xml
fiscal_epos_print/views/point_of_sale.xml

https://github.com/OCA/l10n-italy/issues/1857
--

[12.0] fiscal_epos_print: lotteria degli scontrini + RT XML 7

---

l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
l10n_it_fatturapa_in/tests/data/IT05979361218_014.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in_rc/tests/data/IT01234567890_FPR04.xml
l10n_it_fatturapa_in_rc/tests/test_fatturapa_in_rc.py
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00015.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00016.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00018.xml
l10n_it_fatturapa_out_wt/tests/data/IT06363391001_00019.xml

Descrizione del problema o della funzionalità: alcune nature non sono più utilizzabili anche se ancora presenti per motivi storici
--

[12.0][FIX] demo nature data remove no more selectable

---

l10n_it_fiscal_document_type/data/fiscal.document.type.csv
l10n_it_fiscal_document_type/models/account_invoice.py
l10n_it_fiscal_document_type/models/fiscal_document_type.py
l10n_it_fiscal_document_type/tests/test_doc_type.py
l10n_it_fiscal_document_type/views/fiscal_document_type_view.xml

https://github.com/OCA/l10n-italy/issues/2072
--

[12.0][IMP] Migliorie tipi documenti fiscali - nota credito

---

l10n_it_withholding_tax/views/account.xml

12.0 11078 remove out invoice

---

l10n_it_reverse_charge/models/account_invoice.py

:warning: aggiornare la traduzione subito dopo il merge
--

[12.0] IMP generate_self_invoice message for massive validation

---

l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/tests/test_intrastat_statement.py
l10n_it_intrastat_statement/views/intrastat.xml

Fix https://github.com/OCA/l10n-italy/issues/2120 per v10
--

[10.0][FIX] l10n_it_intrastat_statement: trasporto non obbligatorio, default per natura transazione

---

l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/tests/test_intrastat_statement.py
l10n_it_intrastat_statement/views/intrastat.xml

Closing https://github.com/OCA/l10n-italy/issues/1880 per v10.
--

[10.0][FIX] l10n_it_intrastat_statement: supply and payment method are mandatory

---

l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py

[12.0] IMP l10n_it_vat_statement_communication: interessi quarto trimestre in liquidazioni trimestrali

---

fiscal_epos_print_fiscalcode/__manifest__.py
fiscal_epos_print_fiscalcode/models/res_partner.py
fiscal_epos_print_fiscalcode/readme/CONTRIBUTORS.rst
fiscal_epos_print_fiscalcode/static/src/xml/pos.xml

[12.0] IMP fiscal_epos_print_fiscalcode: allow user to set epos_print_fiscalcode_receipt without going to backend

---

l10n_it_intrastat_statement/readme/DESCRIPTION.rst
l10n_it_intrastat_statement/views/intrastat.xml

Fix https://github.com/OCA/l10n-italy/issues/2123 per v10
--

[10.0][FIX] l10n_it_intrastat_statement: campi facoltativi per sezioni 3 e 4

---

l10n_it_fatturapa_out_rc/tests/data/IT10538570960_00004.xml
l10n_it_fatturapa_out_rc/tests/test_e_invoice_out_rc.py
l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py

Descrizione del problema o della funzionalità: vedi https://github.com/OCA/l10n-italy/issues/1937#issuecomment-785326381
--

[12.0][FIX] l10n it fatturapa out rc verso extra ue

---

l10n_it_ddt/data/ddt_data.xml
l10n_it_ddt/models/stock_picking_package_preparation.py

[12.0] IMP l10n_it_ddt with sequence based on date ranges

---

.travis.yml

https://github.com/OCA/l10n-italy/issues/2169
--

[IMP] Travis - Use Python 3.6

---

l10n_it_vat_registries/tests/test_registry.py

https://github.com/OCA/l10n-italy/issues/1921
--

[11.0] [FIX] l10n_it_vat_registries - Test on midnight

---

l10n_it_fiscal_document_type/data/fiscal.document.type.csv
l10n_it_fiscal_document_type/models/account_invoice.py
l10n_it_fiscal_document_type/models/fiscal_document_type.py
l10n_it_fiscal_document_type/tests/test_doc_type.py
l10n_it_fiscal_document_type/views/fiscal_document_type_view.xml

https://github.com/OCA/l10n-italy/issues/2072
--

[11.0][IMP] Migliorie tipi documenti fiscali - nota credito

---

l10n_it_vat_registries/tests/test_registry.py

https://github.com/OCA/l10n-italy/issues/1921
--

[12.0] [FIX] l10n_it_vat_registries - Test on midnight

---

l10n_it_intrastat/views/config.xml

[12.0] IMP l10n_it_intrastat moving intrastat fields to dedicated tab

---

l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/readme/DESCRIPTION.rst
l10n_it_intrastat_statement/tests/test_intrastat_statement.py
l10n_it_intrastat_statement/views/intrastat.xml

https://github.com/OCA/l10n-italy/issues/2120
+
https://github.com/OCA/l10n-italy/issues/1880
+
https://github.com/OCA/l10n-italy/issues/2123
--

[12.0] [FIX] l10n_it_intrastat_statement: transport code not mandatory, default value for transaction nature + test

---

l10n_it_intrastat_statement/models/intrastat_statement.py

Descrizione del problema o della funzionalità: il report potrebbe essere non ordinato correttamente per sezione
Comportamento attuale prima di questa PR: non si è sicuri dell'ordinamento
Comportamento desiderato dopo questa PR: l'ordinamento è sicuro
--

[12.0][FIX] intrastat statement report section order

---

l10n_it_intrastat_statement/models/intrastat_statement.py

Closing https://github.com/OCA/l10n-italy/issues/2180 for `10.0`.

[10.0][FIX] intrastat statement report section order

---

l10n_it_account/models/account_account.py
l10n_it_account/models/account_group.py

[12.0] IMP l10n_it_account showing which accounts have wrong sign

---

l10n_it_intrastat/models/account.py
l10n_it_intrastat/models/intrastat.py
l10n_it_intrastat/views/product.xml

[12.0] l10n_it_intrastat migliorie interfaccia

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Closing https://github.com/OCA/l10n-italy/issues/2186 for `12.0.`

[FIX] l10n_it_fatturapa_in: fix https://github.com/OCA/l10n-italy/issues/2186

---

l10n_it_fatturapa/models/account.py

Self-explaining.
Dovrei firmalo Tafazzi questo commit. 
https://github.com/OCA/l10n-italy/pull/1984#discussion_r606643511
--

[12.0][FIX] typo: taget -> target

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Otherwise invoice creation is blocked by missing account for invoice line
--

[12.0] IMP _addGlobalDiscount when vendor journal does not have default accounts

---

account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/views/account_view.xml
account_vat_period_end_statement/views/report_vatperiodendstatement.xml
l10n_it_vat_statement_communication/models/comunicazione_liquidazione.py

and
l10n_it_vat_statement_communication: retrieve computation method from VAT statement
--

[12.0] account_vat_period_end_statement: print down payment and computation method

---

l10n_it_withholding_tax_payment/models/withholding_tax.py
l10n_it_withholding_tax_payment/views/withholding_tax.xml

Descrizione del problema o della funzionalità: 
Vedi ISSUE #1998 
--

[8.0][IMP] l10n_it_withholding_tax_payment: UI improve

---

l10n_it_invoices_data_communication/wizard/export_file.py

Descrizione del problema o della funzionalità: stesso problema di #2239
--

[FIX][12.0] l10n_it_invoices_data_communication file export

---

l10n_it_vat_statement_communication/wizard/export_file.py

Descrizione del problema o della funzionalità: rif. #2239
--

[FIX][12.0] l10n_it_vat_statement_communication file export

---

l10n_it_fatturapa_pec/models/fetchmail.py

https://github.com/OCA/l10n-italy/issues/1745
Il processamento delle mail può produrre problemi di integrità nel DB, questa PR evita il problema facendo rollback in caso di eccezioni, ad esempio:
1. Creare un partner **test** con codice REA e ufficio REA
2. Importare con il server fetchmail una fattura in cui il fornitore ha gli stessi valori REA di **test**
Durante l'importazione della email il DB viene corrotto, il messaggio di errore non viene salvato e il CRON di importazione delle email si ferma
Il messaggio di errore
```
duplicate key value violates unique constraint "res_partner_rea_code_uniq"#012DETAIL:  Key (rea_office, rea_code, …
```

[10.0][FIX] l10n_it_fatturapa_pec: Rollback unwanted DB changes in case of exception

---

l10n_it_fatturapa_in/models/partner.py
l10n_it_fatturapa_in/tests/data/IT01234567890_FPR14.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/partner_view.xml
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml

https://github.com/OCA/l10n-italy/issues/2242
--

[12.0] IMP l10n_it_fatturapa_in when importing XML with many decimal digits in prices, causing inconsistencies in total amounts

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/2264
--

[12.0] FIX l10n_it_fatturapa_in in multi company env where partners are shared between companies

---

l10n_it_fatturapa/migrations/13.0.1.0.0/post-migrate.py

[14.0] l10n_it_fatturapa: the second UPDATE does not depend on "table, column" and should be executed only once

---

l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py

[12.0] FIX l10n_it_fatturapa_out_ddt if a default fiscal doc type for "fattura differita"  is already applied, do not overwrite

---

l10n_it_fatturapa_in/views/account_view.xml

https://github.com/OCA/l10n-italy/issues/2291
--

[12.0] IMP l10n_it_fatturapa_in better views for DettaglioPagamento in e-bill details

---

l10n_it_fatturapa_in/tests/data/IT01234567890_FPR16.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

https://github.com/OCA/l10n-italy/issues/2288
--

[12.0] FIX l10n_it_fatturapa_in when importing TIN with double "IT"

---

account_invoice_report_ddt_group/models/account_invoice.py

Closing https://github.com/OCA/l10n-italy/issues/1477 for v10.0
--

[10.0] FIX account_invoice_report_ddt_group when invoicing services

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

This is possible by "sidebar" actions
https://github.com/OCA/l10n-italy/issues/2301
--

[12.0] IMP l10n_it_fatturapa_out: prevent to export XML for vendor bills.

---

l10n_it_account/models/account_tax.py
l10n_it_account/tests/test_l10n_it_account.py
l10n_it_vat_registries_split_payment/tests/test_sp.py

https://github.com/OCA/l10n-italy/issues/2276
--

[14.0] FIX tax balance for partially deductible VAT

---

l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/tests/test_intrastat_statement.py

https://github.com/OCA/l10n-italy/issues/2293 per `10.0`
--

[10.0][FIX] l10n_it_intrastat_statement: la rettifica può essere legata a un periodo di tipo diverso

---

l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Fix https://github.com/OCA/l10n-italy/issues/2267
--

[12.0][IMP] l10n_it_fatturapa_in: Errore parlante se manca configurazione del conto

---

fiscal_epos_print_meal_voucher/__init__.py
fiscal_epos_print_meal_voucher/__manifest__.py
fiscal_epos_print_meal_voucher/models/__init__.py
fiscal_epos_print_meal_voucher/models/account_bank_statement.py
fiscal_epos_print_meal_voucher/models/account_journal.py
fiscal_epos_print_meal_voucher/models/pos_order.py
fiscal_epos_print_meal_voucher/readme/CONTRIBUTORS.rst
fiscal_epos_print_meal_voucher/readme/DESCRIPTION.rst
fiscal_epos_print_meal_voucher/static/src/js/models.js
fiscal_epos_print_meal_voucher/static/src/js/screens.js
fiscal_epos_print_meal_voucher/static/src/xml/pos.xml
fiscal_epos_print_meal_voucher/views/account_views.xml
fiscal_epos_print_meal_voucher/views/assets.xml

Questo modulo Consente di controllare e comunicare al registratore telematico le informazioni relative ai buoni pasto.
--

[12.0] ADD fiscal_epos_print_meal_voucher

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Sono rimasti riferimenti a invoice_line_tax_ids
--

[14.0] [FIX] l10n_it_fatturapa_in: porting fixes

---

l10n_it_fiscalcode/model/res_partner.py

Forward port of #2253, fix for #2250
--

[14.0] [FIX] l10n_it_fiscalcode: codice fiscale per la persona dovrebbe avere caratteri in maiuscolo

---

l10n_it_account_tax_kind/view/account_tax_view.xml

Forward port of #2322, solution for #2323
--

[14.0] [IMP] l10n_it_account_tax_kind: allow to search and group taxes by kind_id

---

l10n_it_rea/models/res_partner.py
l10n_it_rea/tests/test_rea.py

Forward port of #2257, fix for #2256
--

[14.0][FIX] l10n_it_rea: Unicità codice REA solo per partner attivi

---

l10n_it_rea/models/res_partner.py
l10n_it_rea/tests/__init__.py
l10n_it_rea/tests/test_rea.py

Fix https://github.com/OCA/l10n-italy/issues/2256
--

[10.0][FIX] l10n_it_rea: Unicità codice REA solo per partner attivi

---

l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
l10n_it_delivery_note/models/stock_delivery_note.py
l10n_it_delivery_note/readme/USAGE.rst

Closing https://github.com/OCA/l10n-italy/issues/2299 for `14.0`.

[14.0][FIX] l10n_it_delivery_note: some minor fixes

---

l10n_it_delivery_note/cli/migrate_l10n_it_ddt.py
l10n_it_delivery_note/models/stock_delivery_note.py
l10n_it_delivery_note/readme/USAGE.rst

Closing https://github.com/OCA/l10n-italy/issues/2299 for `12.0`.

[12.0][FIX] l10n_it_delivery_note: some minor fixes

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Forward-port of #2187, fix for #2186
--

[FIX] l10n_it_fatturapa_in: solleva errore quando si archivia un template con fornitore collegato

---

l10n_it_delivery_note/models/sale_order.py

According to https://github.com/odoo/odoo/commit/1bf2bfd2a1b72d8f3954ba79a0f116ee579d4e14#diff-10b2bbc33d35a6945f223d38901a2de33fffe78db172d3b939edf0b65aa48c05R575
--

[14.0] [FIX] l10n_it_delivery_note: update method signature

---

fiscal_epos_print_meal_voucher/__manifest__.py
fiscal_epos_print_meal_voucher/models/__init__.py
fiscal_epos_print_meal_voucher/models/point_of_sale.py
fiscal_epos_print_meal_voucher/readme/CONFIGURE.rst
fiscal_epos_print_meal_voucher/readme/DESCRIPTION.rst
fiscal_epos_print_meal_voucher/static/src/js/screens.js
fiscal_epos_print_meal_voucher/static/src/xml/pos.xml
fiscal_epos_print_meal_voucher/views/pos_config_views.xml

[12.0] IMP fiscal_epos_print_meal_voucher allowing to add "ticket credit" to receipt

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Forward port of #2382, fix for #2375
--

[14.0] [FIX] l10n_it_fatturapa_in: add street number to the address field

---

l10n_it_account_balance_report/report/account_balance_report_xlsx.py

Lesser update to .xlsx reports: use numerical values (instead of strings) for cells that contains amounts
--

[12.0][UPD] account_balance_report: use numerical values in .xlsx reports

---

l10n_it_fatturapa_out_ddt/__manifest__.py
l10n_it_fatturapa_out_ddt/models/__init__.py
l10n_it_fatturapa_out_ddt/models/company.py
l10n_it_fatturapa_out_ddt/models/fattura_differita_ddt.py
l10n_it_fatturapa_out_ddt/readme/CONFIGURE.rst
l10n_it_fatturapa_out_ddt/views/res_config_settings_views.xml

Sometimes user may want to use the default computation of l10n_it_fiscal_document_type
--

[12.0] IMP l10n_it_fatturapa_out_ddt allowing to disable "Automatically set document type for deferred invoices".

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Fix issue [https://github.com/OCA/l10n-italy/issues/1828](https://github.com/OCA/l10n-italy/issues/1828)
--

Fix issue https://github.com/OCA/l10n-italy/issues/1828

---

fiscal_epos_print/views/account.xml

[12.0] FIX fiscal_epos_print: fiscalprinter_payment_index must be set also for Discount on payment

---

l10n_it_fatturapa/readme/INSTALL.rst

Istruzioni per risolvere https://github.com/OCA/l10n-italy/issues/2324
--

[14.0][IMP] l10n_it_fatturapa: Istruzioni per problemi con l10n_it_edi

---

l10n_it_fiscal_document_type/migrations/13.0.1.0.0/post-migration.py

[14.0][FIX] l10n_it_fiscal_document_type: data migration script

---

l10n_it_fatturapa/models/account.py
l10n_it_fatturapa_in/views/account_view.xml

https://github.com/OCA/l10n-italy/issues/2291
--

[12.0] Better view of payments list

---

l10n_it_withholding_tax/models/withholding_tax.py
l10n_it_withholding_tax/tests/test_withholding_tax.py

https://github.com/OCA/l10n-italy/issues/2494

[12.0] IMP l10n_it_withholding_tax while duplicating withholding tax, add (copy) suffix to code

---

l10n_it_fiscal_document_type/models/account_move.py
l10n_it_fiscal_document_type/tests/test_doc_type.py

[14.0][FIX] l10n_it_fiscal_document_type: Tipo documento impostato dall'utente non mantenuto 

---

l10n_it_account_stamp/__manifest__.py
l10n_it_account_stamp/views/account_invoice_report.xml

https://github.com/OCA/l10n-italy/issues/2522

[12.0] IMP l10n_it_account_stamp: print legal statement in invoice report

---

l10n_it_website_portal_corrispettivi/__init__.py
l10n_it_website_portal_corrispettivi/__manifest__.py
l10n_it_website_portal_corrispettivi/controllers/__init__.py
l10n_it_website_portal_corrispettivi/controllers/main.py
l10n_it_website_portal_corrispettivi/models/__init__.py
l10n_it_website_portal_corrispettivi/models/res_partner.py
l10n_it_website_portal_corrispettivi/readme/DESCRIPTION.rst
l10n_it_website_portal_corrispettivi/views/l10n_it_website_portal_corrispettivi_templates.xml
setup/l10n_it_website_portal_corrispettivi/odoo/addons/l10n_it_website_portal_corrispettivi
setup/l10n_it_website_portal_corrispettivi/setup.py

[12.0] ADD l10n_it_website_portal_corrispettivi: Aggiunge ricevuta o fattura come opzione nel profilo dell'utente portale

---

l10n_it_fatturapa_out/data/invoice_it_template.xml
l10n_it_fatturapa_out/tests/fatturapa_common.py
l10n_it_fatturapa_out/tests/test_fatturapa_out_noteline.py

Risolve https://github.com/OCA/l10n-italy/issues/2529 per `14.0`

[FIX] l10n_it_fatturapa_out: Esportazione fattura con natura esenzione

---

l10n_it_reverse_charge/models/account_move.py
l10n_it_reverse_charge/tests/test_rc.py

See [https://github.com/OCA/l10n-italy/issues/2575](https://github.com/OCA/l10n-italy/issues/2575)

[14.0][FIX] l10n_it_reverse_charge: undo reverse moves when supplier invoice is reset to draft

---

l10n_it_account/models/account_tax.py
l10n_it_account/tests/test_l10n_it_account.py

[14.0][FIX] l10n_it_account: Importi (in)detraibili per liquidazione IVA multi periodo

---

l10n_it_fatturapa_in/views/account_view.xml

Il campi aggiuntivi sono mal posizionati. Vd. #2585

[FIX] l10n_it_fatturapa_in: field positioning in view

---

l10n_it_sdi_channel/models/sdi.py

Dipende da https://github.com/OCA/l10n-italy/pull/2594
TODO

[12.0] IMP l10n_it_sdi_channel making first_invoice_sent more clear

---

l10n_it_account_stamp/readme/CONFIGURE.rst
l10n_it_account_stamp/readme/CONTRIBUTORS.rst
l10n_it_account_stamp/views/product_view.xml

Fix https://github.com/OCA/l10n-italy/issues/2580

[14.0][IMP] l10n_it_account_stamp, move fields on accountig tab

---

l10n_it_withholding_tax/models/account.py

Risolve https://github.com/OCA/l10n-italy/issues/2616 per `14.0`.
Risolve anche altri due diversi potenziali problemi, notati durante la risoluzione di https://github.com/OCA/l10n-italy/pull/2617#pullrequestreview-865426359:
- "TypeError: 'bool' object is not iterable"
- "AttributeError: 'bool' object has no attribute 'date'"

[FIX] l10n_it_withholding_tax: Prevenire "AttributeError: 'bool' object has no attribute 'id'"

---

fiscal_epos_print/models/account.py
fiscal_epos_print/readme/CONTRIBUTORS.rst

[12.0][FIX] fiscal_epos_print, missing translation

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/tests/data/IT02780790107_11008.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/account_view.xml

Self invoices should not be re-imported with SdI sends them back.
Fix for #2552

[14.0][FIX] l10n_it_fatturapa_in: show if a file contains self invoices

---

l10n_it_fatturapa_out_rc/models/account_move.py

Fix https://github.com/OCA/l10n-italy/issues/2631

[14.0][FIX] l10n_it_fatturapa_out_rc: skip preventive checks when there are no invoices with rc

---

l10n_it_declaration_of_intent/models/account_move.py
l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py

step di riproduzione:
- creare una dichiarazione con partnerA
- creare fattura con partnerA e confermare
- portare in bozza la fattura e riconfermare
risultato osservato:
la dichiarazione riporta 2 righe con stessa fattura
dopo questa PR:
la dichiarazione riporterà 1 solo riga per fattura.

[14.0][FIX] l10n_it_declaration_of_intent: duplicated line_ids

---

l10n_it_dichiarazione_intento/__manifest__.py
l10n_it_dichiarazione_intento/models/dichiarazione_intento.py
l10n_it_dichiarazione_intento/security/declaration_security.xml
l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py

Risolve https://github.com/OCA/l10n-italy/issues/2578 per `12.0`.
Backporting di https://github.com/OCA/l10n-italy/pull/2582 + test.
Per correggere runboat c'è https://github.com/OCA/l10n-italy/pull/2594.

[12.0][IMP] l10n_it_dichiarazione_intento: Supporto per multi-company

---

l10n_it_account/reports/account_reports_view.xml

[14.0][IMP] l10n_it_account: manage multi-company report

---

l10n_it_declaration_of_intent/__manifest__.py
l10n_it_declaration_of_intent/models/declaration.py
l10n_it_declaration_of_intent/security/declaration_security.xml
l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py

[IMP] added declaration multi-company rules

---

l10n_it_fatturapa_in/models/attachment.py

fix https://github.com/OCA/l10n-italy/issues/2699
superseed: https://github.com/OCA/l10n-italy/pull/2701
--

[12.0][FIX] l10n_it_fatturapa_in, skip registered invoice in _compute_xml_data

---

l10n_it_withholding_tax/models/withholding_tax.py

And
FIX ValueError: Expected singleton: withholding.tax.move(ID1, ID2)
https://github.com/OCA/l10n-italy/issues/2671

[12.0] REF l10n_it_withholding_tax withholding.tax display_name with cleaner implementation

---

l10n_it_dichiarazione_intento/models/account_invoice.py
l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py

Risolve https://github.com/OCA/l10n-italy/issues/2547 per `10.0`.

[10.0] l10n_it_dichiarazione_intento: Validazione massiva di fatture

---

l10n_it_ricevute_bancarie/migrations/14.0.1.0.1/post-migration.py
l10n_it_ricevute_bancarie/models/account.py
l10n_it_ricevute_bancarie/tests/riba_common.py
l10n_it_ricevute_bancarie/tests/test_riba.py
l10n_it_ricevute_bancarie/views/account_view.xml
l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py

Manage multiple bank
https://github.com/OCA/l10n-italy/issues/2707

[14.0][IMP] l10n_it_ricevute_bancarie: manage multiple bank in partner, migration script

---

l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py

Closing https://github.com/OCA/l10n-italy/issues/2749 for `14.0`

[14.0][FIX] l10n_it_fatturapa_pec when e-invoice sent file name is in wrong format

---

fiscal_epos_print/static/src/js/epson_epos_print.js

https://discord.com/channels/753902328494424064/776479965411541004/956498944257564673

[12.0] FIX fiscal_epos_print : be sure to push order to server

---

l10n_it_delivery_note/models/stock_delivery_note.py

Descrizione del problema o della funzionalità: fixes #2802
--

[12.0][FIX] l10n_it_delivery_note rec_name

---

l10n_it_vat_registries/models/vat_registry.py

[14.0][IMP] l10n_it_vat_registries: print purchase vat registries with ref in INV. NUM.

---

l10n_it_intrastat/models/__init__.py
l10n_it_intrastat/models/sale_order.py
l10n_it_intrastat/readme/CONTRIBUTORS.rst
l10n_it_intrastat/tests/test_intrastat.py

fix https://github.com/OCA/l10n-italy/issues/2807

[14.0][fix]l10n_intrastat, update intrastat field when invoicing from sale order

---

l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py

Corregge https://github.com/OCA/l10n-italy/issues/2630 per `12.0`.
È quanto di più simile a un cherry-pick di https://github.com/OCA/l10n-italy/commit/ee135bd296019375eb787da5bf06b8326778b5ad sono riuscito a fare.

[IMP] l10n_it_fatturapa_in_rc: support for Natura N2.1

---

l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py

Risolve https://github.com/OCA/l10n-italy/issues/2836 per `14.0`.

[FIX] l10n_it_fatturapa_pec: Attachment might be a string

---

l10n_it_account_balance_report/__manifest__.py
l10n_it_account_balance_report/data/account_type.xml
l10n_it_account_balance_report/migrations/12.0.1.0.5/post-migrate.py
l10n_it_account_balance_report/report/account_balance_report.py
l10n_it_account_balance_report/report/account_balance_report_xlsx.py
l10n_it_account_balance_report/report/templates/account_balance_report.xml

Corregge https://github.com/OCA/l10n-italy/issues/2831 per `12.0`.

[FIX] Il resoconto dello stato patrimoniale non tiene conto degli anni precedenti

---

l10n_it_fatturapa_out/tests/fatturapa_common.py
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
l10n_it_fatturapa_sdicoop/tests/__init__.py
l10n_it_fatturapa_sdicoop/tests/test_account_invoice.py
l10n_it_sdi_channel/__manifest__.py
l10n_it_sdi_channel/models/__init__.py
l10n_it_sdi_channel/models/account_invoice.py
l10n_it_sdi_channel/models/company.py
l10n_it_sdi_channel/security/security.xml
l10n_it_sdi_channel/tests/__init__.py
l10n_it_sdi_channel/tests/test_account_invoice.py
l10n_it_sdi_channel/views/account_invoice_views.xml
l10n_it_sdi_channel/views/company_view.xml

Risolve https://github.com/OCA/l10n-italy/issues/2875 per `12.0`

Pulsante per validare e inviare le fatture a SdI

---

l10n_it_delivery_note/models/stock_delivery_note.py

Descrizione del problema o della funzionalità: #2805
--

[12.0][FIX] l10n_it_delivery_note display_name depends on itself

---

l10n_it_delivery_note/__manifest__.py

l10n_it_delivery_note: Rimuovere Byloth dai maintainer

---

l10n_it_fatturapa_in/models/partner.py
l10n_it_fatturapa_in/tests/data/IT01234567890_x05mX.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Risolve https://github.com/OCA/l10n-italy/issues/2909

[FIX] Controllo IdFiscaleIVA solo per fornitori italiani

---

l10n_it_fatturapa_in/wizard/link_to_existing_invoice.xml

Risolve https://github.com/OCA/l10n-italy/issues/2026 per `14.0`.

[14.0][IMP] ability to link already open vendor invoices from xml received

---

l10n_it_fatturapa_out/views/account_view.xml

stato dell'e-fattura non presente il lista note credito
--

[14.0][ADD] l10n_it_fatturapa_out: aggiunto stato e-fattura in lista note credito

---

l10n_it_intrastat/README.rst
l10n_it_intrastat/__manifest__.py
l10n_it_intrastat/data/account.intrastat.transaction.nature.b.csv
l10n_it_intrastat/data/account.intrastat.transaction.nature.csv
l10n_it_intrastat/models/account.py
l10n_it_intrastat/models/config.py
l10n_it_intrastat/models/intrastat.py
l10n_it_intrastat/readme/CONTRIBUTORS.rst
l10n_it_intrastat/security/ir.model.access.csv
l10n_it_intrastat/static/description/index.html
l10n_it_intrastat/views/account.xml
l10n_it_intrastat/views/config.xml
l10n_it_intrastat/views/intrastat.xml
l10n_it_intrastat_statement/models/intrastat_statement.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section1.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section3.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section1.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section2.py
l10n_it_intrastat_statement/models/intrastat_statement_section.py
l10n_it_intrastat_statement/readme/CONTRIBUTORS.rst
l10n_it_intrastat_statement/readme/DESCRIPTION.rst
l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
l10n_it_intrastat_statement/tests/test_intrastat_statement.py
l10n_it_intrastat_statement/views/intrastat.xml

Task list:
```
2022-07-06 14:07:21,839 280 ERROR odoo odoo.addons.l10n_it_intrastat_statement.tests.test_intrastat_statement: FAIL: TestIntrastatStatement.test_statement_purchase
File "/__w/l10n-italy/l10n-italy/l10n_it_intrastat_statement/tests/test_intrastat_statement.py", line 179, in test_statement_purchase
self.assertEqual(len(file_content.splitlines()[-1]), 119)
AssertionError: 131 != 119
2022-07-06 14:07:21,840 280 INFO odoo odoo.addons.l10n_it_intrastat_statement.tests.test_intrastat_statement: Starting TestIntrastatStatement.test_statement_purchase_currency ... 
2022-07-06 14:07:23,061 280 INFO odoo odoo.addons.l10n_it_intrastat_statement.tests.test_intrastat_statement: Starting TestIntrastatStatement.test_statement_purchase_quarter ... …
```

[14.0][IMP] Intrastat 2022

---

l10n_it_account/models/account_tax.py

Sostituisce https://github.com/OCA/l10n-italy/pull/2799 e risolve https://github.com/OCA/l10n-italy/issues/2577.

[FIX] l10n_it_account: fix error during vat statement calculation

---

l10n_it_split_payment/migrations/14.0.1.0.0/post-migration.py
l10n_it_split_payment/readme/CONTRIBUTORS.rst

Fix migration script, check if move lines exists in order to avoid () in query

14.0-fix-l10n_it_split_payments-migration_script_issue

---

l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Eventuali errori o incongruenze nelle informazioni relative alla banca or al conto per i pagamenti (es: IBAN già esistente nel sistema, ma associato ad un partner diverso), non dovrebbe impedire l'importazione della fattura dall'XML ricevuto dallo SdI.
In alcuni caso, ad es. MP20 come tipo, il beneficiario è il cessionario/committente (ossia l'azienda che importa la fattura) e l'IBAN indicato non è associato al cedente/prestatore, quando odoo prova a crearlo, fallisce la clausola unique a livello SQL. In ogni caso la fattura andrebbe importata.
Il processo di importazione non si interrompe.
Probabilmente risolve #1359 (per la 12.0)
--
Confermo di aver firmato …

[FIX][l10n_it_fatturapa_in] do not fail import of XML e-invoice on missing/wrong bank account information

---

l10n_it_reverse_charge/models/account_invoice.py
l10n_it_reverse_charge/views/account_invoice_view.xml

https://github.com/OCA/l10n-italy/issues/2903

[12.0] IMP l10n_it_reverse_charge showing info about original supplier invoice

---

l10n_it_fatturapa_in/tests/__init__.py
l10n_it_fatturapa_in/tests/test_fix_bad_uris.py
l10n_it_fatturapa_in/wizard/efattura.py

Adattamento di #2940 per la 14.0
Co-authored-by: Borruso <gborruso@dinamicheaziendali.it>

[14.0][FIX] l10n_it_fatturapa_in: fix invalid URIs

---

l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Risolve: https://github.com/OCA/l10n-italy/issues/3013

[FIX][l10n_it_fatturapa_in] fix fiscal position  parameter

---

.copier-answers.yml
.pre-commit-config.yaml

In order to include https://github.com/OCA/oca-addons-repo-template/pull/170

[16.0] Update from copier template

---

l10n_it_location_nuts/__manifest__.py

[14.0] [FIX] category in manifest file

---

l10n_it_fatturapa/models/ir_attachment.py
l10n_it_fatturapa/views/fatturapa_attachment_views.xml
l10n_it_fatturapa_in/views/account_view.xml

[12.0] [FIX] XML "show preview" not translatable

---

.copier-answers.yml
.github/workflows/pre-commit.yml
.github/workflows/test.yml

Descrizione del problema o della funzionalità: errore nell'installazione dei test per versione python non trovata
--

[12.0][UPD] copier

---

l10n_it_fatturapa_out_welfare/tests/test_fatturapa_out_welfare.py

Risolve https://github.com/OCA/l10n-italy/issues/3113 per `12.0`.

[FIX] Nei test, c'è un conflitto di sequenze fattura

---

l10n_it_delivery_note/__manifest__.py
l10n_it_delivery_note/models/account_invoice.py
l10n_it_delivery_note/models/sale_order.py
l10n_it_delivery_note/models/stock_delivery_note.py
l10n_it_delivery_note/tests/test_stock_delivery_note_invoicing.py
l10n_it_delivery_note/wizard/__init__.py
l10n_it_delivery_note/wizard/delivery_note_invoice.py
l10n_it_delivery_note/wizard/delivery_note_invoice.xml

Descrizione del problema o della funzionalità: duplicato di #3049 con recupero codice da #2346 e con miglioramenti su raggruppamento righe
--

[12.0][BACK] l10n_it_delivery_note invoice from ddt

---

l10n_it_ddt/models/stock_picking_package_preparation.py
l10n_it_ddt/tests/test_ddt.py
l10n_it_ddt/views/stock_picking_package_preparation.xml
l10n_it_ddt/wizard/ddt_from_picking.py

Implementa https://github.com/OCA/l10n-italy/issues/3133 per `12.0`.

[IMP] Impostare una nota predefinita per il DdT nel tipo DdT

---

l10n_it_declaration_of_intent/models/account_move.py
l10n_it_declaration_of_intent/readme/CONTRIBUTORS.rst

Risolve; https://github.com/OCA/l10n-italy/issues/3055

[FIX][l10n_it_declaration_of_intent] fix creditnote sign

---

l10n_it_fatturapa_in/models/attachment.py

Aggiunge i codici al riconoscimento autofattura per il filtro in import.

[14.0] [IMP] l10n_it_fatturapa_in: add TD27 TD28

---

l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml

[12.0][FIX] l10n_it_intrastat_statement | report did not show corret county

---

l10n_it_fatturapa_in/tests/data/IT03309970733_VATG1.xml
l10n_it_fatturapa_in/tests/data/IT03309970733_VATG2.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py

Sostituisce https://github.com/OCA/l10n-italy/pull/1676, abbandonata da più di due anni.
Risolve https://github.com/OCA/l10n-italy/issues/1667 per `12.0`.
Risolve https://github.com/OCA/l10n-italy/issues/3146 per `12.0`.

[12.0] [FIX]  l10n_it_fatturapa_in - Gruppi IVA

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/views/account_view.xml
l10n_it_fatturapa_in_rc/models/__init__.py
l10n_it_fatturapa_in_rc/models/attachment.py
l10n_it_fatturapa_out_rc/models/account_move.py
l10n_it_reverse_charge/models/account_move.py
l10n_it_reverse_charge/models/account_rc_type.py
l10n_it_reverse_charge/tests/__init__.py
l10n_it_reverse_charge/tests/rc_common.py
l10n_it_reverse_charge/tests/test_account_rc_type.py
l10n_it_reverse_charge/tests/test_rc.py
l10n_it_reverse_charge/views/account_rc_type_view.xml

[14.0] l10n_it_reverse_charge supporting "with_supplier_self_invoice" for e-invoices + link supplier self invoice to e-invoice 

---

.copier-answers.yml
.pre-commit-config.yaml

See https://github.com/OCA/oca-addons-repo-template

Updated from copier template

---

assets_management/wizard/account_move_manage_asset.py

[FIX][14.0] assets_management sale

---

assets_management/wizard/account_move_manage_asset.py

Errore nel calcolo del tipo di movimento
--

[14.0][FIX] assets_management: fix move_type during update asset

---

l10n_it_reverse_charge/models/account_move.py
l10n_it_reverse_charge/views/account_move_views.xml

https://github.com/OCA/l10n-italy/issues/2903
Forward-port-of: #2904

[14.0] [IMP] l10n_it_reverse_charge: showing info about original supplier invoice

---

account_vat_period_end_statement/views/report_vatperiodendstatement.xml

https://github.com/OCA/l10n-italy/issues/3232

[16.0][FIX] account_vat_period_end_statement: fix align amounts

---

l10n_it_reverse_charge/__manifest__.py

[14.0][FIX] l10n_it_reverse_charge: fix website in manifest

---

l10n_it_fatturapa_in_rc/__manifest__.py

[14.0][FIX] l10n_it_fatturapa_in_rc: fix website in manifest

---

assets_management/__manifest__.py

[14.0] [FIX] assets_management: fix website in manifest

---

l10n_it_fatturapa_in/__manifest__.py

[14.0][FIX] l10n_it_fatturapa_in: fix website in manifest

---

l10n_it_intrastat/models/account.py
l10n_it_intrastat/views/account.xml
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section1.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section1.py

[14.0][FIX] l10n it intrastat statement: weight can be 0

---

l10n_it_ricevute_bancarie/readme/CONFIGURE.rst
l10n_it_ricevute_bancarie/readme/CONTRIBUTORS.rst
l10n_it_ricevute_bancarie/tests/riba_common.py
l10n_it_ricevute_bancarie/tests/test_riba.py
l10n_it_ricevute_bancarie/views/configuration_view.xml
l10n_it_ricevute_bancarie/views/riba_view.xml

Implementa https://github.com/OCA/l10n-italy/issues/2950 per `12.0`.

[IMP] Ricevute bancarie "Al dopo incasso"

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

La signature di `_render_qweb_pdf` è cambiata: https://github.com/odoo/odoo/commit/ffc525419a71aeb05ede6b59dda9e62286a5e66e
Resolves: #3127
Resolves: #3252

[16.0][FIX] l10n_it_fatturapa_out: report function signature

---

l10n_it_withholding_tax/models/account.py
l10n_it_withholding_tax/tests/test_withholding_tax.py

Risolve https://github.com/OCA/l10n-italy/issues/3070 per `12.0`.

[FIX] Ritenute: Nota di credito non mantiene la ritenuta e genera movimenti

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_out/tests/fatturapa_common.py
l10n_it_fatturapa_out_rc/tests/test_e_invoice_out_rc.py
l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py

Risolve https://github.com/OCA/l10n-italy/issues/3065 per `12.0`.

[FIX] Esportazione autofatture per diversi fornitori

---

l10n_it_fatturapa_out/tests/fatturapa_common.py
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py

[16.0][REF] l10n_it_fatturapa_out: Invoice used in tests is open when validated

---

l10n_it_withholding_tax/models/account.py

#1695 
Co-authored-by: alessandrocamilli <alessandrocamilli@openforce.it>
--

[14.0][FIX] l10n_it_withholding_tax: set wt amount residual in invoice payment wizard

---

l10n_it_delivery_note/models/stock_picking.py
l10n_it_delivery_note/tests/delivery_note_common.py
l10n_it_delivery_note/tests/test_stock_delivery_note.py
l10n_it_delivery_note/wizard/delivery_note_create.py

https://github.com/OCA/l10n-italy/issues/3270

[14.0][IMP]l10n_it_delivery_note: set partner as commercial partner

---

l10n_it_website_portal_ipa/controllers/main.py

https://github.com/odoo/odoo/blob/16.0/addons/portal/controllers/portal.py#L370

[16.0] [FIX] l10n_it_website_portal_ipa: fix method signature

---

l10n_it_withholding_tax/models/account.py
l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
l10n_it_withholding_tax/tests/test_withholding_tax.py

Risolve https://github.com/OCA/l10n-italy/issues/3288 per `14.0`.

[FIX] Dichiarazioni di ritenuta d'acconto duplicate

---

l10n_it_delivery_note/i18n/it.po
l10n_it_delivery_note/models/stock_delivery_note.py

Aggiunto controllo per avere numerazione unica nei DDT.
#3314

14.0 [IMP] l10n_it_delivery_note: aggiunto constraint sul numero DDT

---

l10n_it_delivery_note_rma/__init__.py
l10n_it_delivery_note_rma/__manifest__.py
l10n_it_delivery_note_rma/models/__init__.py
l10n_it_delivery_note_rma/models/rma.py
l10n_it_delivery_note_rma/models/stock_delivery_note.py
l10n_it_delivery_note_rma/models/stock_move.py
l10n_it_delivery_note_rma/readme/CONTRIBUTORS.rst
l10n_it_delivery_note_rma/readme/DESCRIPTION.rst
l10n_it_delivery_note_rma/readme/USAGE.rst
l10n_it_delivery_note_rma/security/ir.model.access.csv
l10n_it_delivery_note_rma/tests/__init__.py
l10n_it_delivery_note_rma/tests/delivery_note_common.py
l10n_it_delivery_note_rma/tests/test_delivery_note_rma.py
l10n_it_delivery_note_rma/views/delivery_views.xml
l10n_it_delivery_note_rma/views/rma_views.xml
l10n_it_delivery_note_rma/wizard/__init__.py
l10n_it_delivery_note_rma/wizard/stock_delivery_note_rma_wizard.py
l10n_it_delivery_note_rma/wizard/stock_delivery_note_rma_wizard_views.xml
oca_dependencies.txt
setup/l10n_it_delivery_note_rma/odoo/addons/l10n_it_delivery_note_rma
setup/l10n_it_delivery_note_rma/setup.py

This module adds:
- the possibility to create one or more RMA(s) from a Delivery Note (from l10n_it_delivery_note, Italian legally required transportation document)
- a link between DN and RMA(s)
- adding an "RMA" smart button in DN to quickly access RMAs created from a specific DN

[14.0][ADD] l10n_it_delivery_note_rma

---

l10n_it_delivery_note/models/stock_delivery_note.py

Aggiunto controllo per avere numerazione unica nei DDT.
#3314

16.0 [IMP] l10n_it_delivery_note: aggiunto constraint sul numero DDT

---

l10n_it_account_stamp/__manifest__.py
l10n_it_account_stamp/views/account_move_report.xml

Port of #2505 from 12.0 to 14.0.

[14.0][FW] [12.0] IMP l10n_it_account_stamp: print legal statement in invoice report

---

l10n_it_account_stamp/__manifest__.py
l10n_it_account_stamp/views/account_move_report.xml

Port of #3423 from 14.0 to 16.0.

[16.0][FW] [14.0][FW] [12.0] IMP l10n_it_account_stamp: print legal statement in invoice report

---

l10n_it_declaration_of_intent/models/account_move.py
l10n_it_declaration_of_intent/readme/CONTRIBUTORS.rst

Risolve: https://github.com/OCA/l10n-italy/issues/3055
--

[16.0] [FIX] l10n_it_declaration_of_intent: fix creditnote sign

---

l10n_it_fatturapa/models/ir_attachment.py

Forward port of: https://github.com/OCA/l10n-italy/pull/2940
See: https://github.com/OCA/l10n-italy/issues/2699

[16.0][FIX] l10n_it_fatturapa: fix not valid URI

---

l10n_it_fatturapa/models/ir_attachment.py

Forward port of: #2940
See: #2699

[14.0][FIX] l10n_it_fatturapa: fix not valid URI

---

l10n_it_withholding_tax/models/withholding_tax.py

Port of #2657 from 12.0 to 14.0.

[14.0][FW] [12.0] REF l10n_it_withholding_tax withholding.tax display_name with cleaner implementation

---

l10n_it_central_journal/views/report_account_central_journal.xml

[14.0] [IMP] l10n_it_central_journal: update logic to set initial line value

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/tests/data/IT02780790107_11009.xml
l10n_it_fatturapa_in/tests/data/IT02780790107_11010.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py

Risolve https://github.com/OCA/l10n-italy/issues/3161 per `12.0`.
Backport di https://github.com/OCA/l10n-italy/pull/3162 + test.
Resolves: #3161

[IMP] fatturapa_in Autofatture per autoconsumo TD27

---

l10n_it_withholding_tax/models/account.py

Forward port di #2572
Resolves: #1695

[16.0][FIX] l10n_it_withholding_tax: set wt amount residual in invoice payment wizard

---

l10n_it_fatturapa_out/data/invoice_it_template.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00016.xml
l10n_it_fatturapa_out/wizard/efattura.py

Fixes: #2971
Forward port of: #2973

[FIX][l10n_it_fatturapa_out] fix FE to private people

---

l10n_it_website_portal_fiscalcode/views/l10n_it_website_portal_fiscalcode_templates.xml

Corregge https://github.com/OCA/l10n-italy/issues/3520 per la versione 12.

12.0 Fix portal fiscalcode label

---

l10n_it_website_portal_fiscalcode/views/l10n_it_website_portal_fiscalcode_templates.xml

Corregge https://github.com/OCA/l10n-italy/issues/3520 per la versione 14.

14.0 Fix portal fiscalcode label

---

account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/readme/CONTRIBUTORS.rst
account_vat_period_end_statement/tests/test_vat_statement.py

Risolve https://github.com/OCA/l10n-italy/issues/2941 per `12.0`.

[FIX] Selezione liquidazione IVA precedente

---

l10n_it_reverse_charge/migrations/13.0.1.0.0/post-migration.py
l10n_it_reverse_charge/migrations/13.0.1.0.0/pre-migration.py

Alcune correzioni sugli script di migrazione, segnalate nei commenti sotto.

[14.0][FIX] l10n_it_reverse_charge migration scripts

---

l10n_it_delivery_note/__manifest__.py

[16.0] [UPD] l10n_it_delivery_note: aggiornato maintainers

---

l10n_it_delivery_note/migrations/13.0.1.0.0/pre-migrate.py

Aggiunto lo script di migrazione.

[14.0][FIX] l10n_it_delivery_note script pre-migrate migration

---

l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/views/account_view.xml

Forward port di modifiche della  #3084

[16.0] IMP l10n_it_reverse_charge supporting with_supplier_self_invoice for e-invoices

---

assets_management/models/asset.py
assets_management/models/asset_depreciation.py
assets_management/report/asset_journal.py
assets_management/report/asset_previsional.py
assets_management/report/templates/asset_journal.xml
assets_management/report/templates/asset_previsional.xml
assets_management/views/asset.xml
assets_management/wizard/account_move_manage_asset.py
assets_management/wizard/account_move_manage_asset_view.xml
assets_management/wizard/asset_journal_report.py
assets_management/wizard/asset_journal_report_view.xml
assets_management/wizard/asset_previsional_report.py
assets_management/wizard/asset_previsional_report_view.xml

Aggiunta possibilità di dismettere direttamente un cespite, pratica fiscalmente prevista (vedi es. https://fiscomania.com/dismissione-beni-aziendali-obsoleti/ le ultime due casistiche).

[14.0][IMP]  assets_management: add ability to dismiss directly an asset

---

.pre-commit-config.yaml
l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/tests/data/ZGEXQROO37831_anonimizzata.xml
l10n_it_fatturapa_in/tests/fatturapa_common.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_in/views/account_view.xml
l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py
l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
l10n_it_fatturapa_pec/models/mail_thread.py
l10n_it_fatturapa_pec/tests/test_e_invoice_response.py

Vd. anche #3118 per le modifiche a `l10n_fatturapa_pec`

[14.0] l10n_it_fatturapa_in: forward port of #2788

---

l10n_it_withholding_tax/__init__.py
l10n_it_withholding_tax/models/account.py
l10n_it_withholding_tax/readme/ROADMAP.rst
l10n_it_withholding_tax/tests/test_withholding_tax.py
l10n_it_withholding_tax/wizards/__init__.py
l10n_it_withholding_tax/wizards/account_payment_register.py

Corregge https://github.com/OCA/l10n-italy/issues/3533 per `14.0`.

[FIX] Nelle fatture con ritenuta, resettare l'importo da pagare al netto da pagare residuo

---

l10n_it_delivery_note/models/stock_delivery_note.py

[16.0][FIX] l10n_it_delivery_note: fix location address

---

l10n_it_delivery_note/models/stock_delivery_note.py

issue di tracciamento: #3551 
--

[16.0][ADD] l10n_it_delivery_note: gross_weight and net_weight computation from pickings

---

l10n_it_fatturapa_in/views/account_view.xml

[16.0][ADD] l10n_it_fatturapa_in: aggiunto totale fatture in tree

---

l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py

[16.0][FIX] l10n_it_declaration_of_intent: controllo dichiarazione solo se tipo fattura

---

l10n_it_delivery_note/__manifest__.py
l10n_it_delivery_note/migrations/16.0.1.1.0/post-migration.py
l10n_it_delivery_note/models/res_partner.py
l10n_it_delivery_note/views/res_partner.xml
l10n_it_delivery_note/views/stock_delivery_note.xml
l10n_it_delivery_note/views/stock_picking.xml

https://github.com/OCA/l10n-italy/issues/3325 for 16.0

[IMP]l10n_it_delivery_note: Add is_carrier on partner and domain

---

l10n_it_delivery_note/views/stock_picking.xml

visualizzazione form picking non corretta
--

[16.0][FIX] l10n_it_delivery_note: fix picking view

---

l10n_it_delivery_note/models/stock_delivery_note.py

[14.0][ADD] l10n_it_delivery_note: gross_weight and net_weight computation from pickings

---

l10n_it_fatturapa_out/migrations/16.0.1.0.9/pre-migrate.py

[16.0][FIX] l10n_it_fatturapa_out - delete database constraint after field changed type

---

l10n_it_riba_sale_commission/__manifest__.py
l10n_it_riba_sale_commission/models/account_move.py
l10n_it_riba_sale_commission/readme/DESCRIPTION.rst
l10n_it_riba_sale_commission/tests/__init__.py
l10n_it_riba_sale_commission/tests/test_riba_sale_commission.py
l10n_it_riba_sale_commission/wizard/wizard_riba_commissions_settle.py

Adegua il calcolo delle provvigioni con data pagamento basandosi sulla scadenza riba + giorni di sicurezza

[IMP][14.0]l10n_it_riba_sale_commission: generazione provvigioni con data pagamento

---

l10n_it_delivery_note/report/report_delivery_note.xml
l10n_it_delivery_note/views/stock_delivery_note.xml

[14.0][FIX]l10n_it_delivery_note: change inconsistent strings

---

l10n_it_withholding_tax_reason/__init__.py
l10n_it_withholding_tax_reason/__manifest__.py
l10n_it_withholding_tax_reason/hooks.py
l10n_it_withholding_tax_reason/migrations/14.0.1.0.0/pre-migration.py

Modifiche per correzione #3354 sulla base dei commenti in https://discord.com/channels/753902328494424064/753902328494424070/1129335720004292660
edit: e da commenti qui https://github.com/OCA/l10n-italy/issues/3574#issuecomment-1719725803

[14.0][FIX] l10n_it_withholding_tax_reason migration script compatibile con apriori

---

l10n_it_delivery_note/models/account_invoice.py
l10n_it_delivery_note/models/stock_delivery_note.py

Risolve: https://github.com/OCA/l10n-italy/issues/2597
--

[14.0][FIX] l10n_it_delivery_note: fix action window

---

l10n_it_financial_statements_report/readme/CONTRIBUTORS.rst
l10n_it_financial_statements_report/tests/test_report.py

Risolve https://github.com/OCA/l10n-italy/issues/3620 per `14.0`.

[REF] Rimuovere file di test temporaneo dai test

---

l10n_it_delivery_note/models/account_invoice.py
l10n_it_delivery_note/models/stock_delivery_note.py

[16.0][FIX] l10n_it_delivery_note: fix action window

---

l10n_it_delivery_note/models/stock_delivery_note.py

Small method that could be useful for further implementations
This is needed on https://github.com/OCA/l10n-italy/pull/3738 and https://github.com/OCA/l10n-italy/pull/3770

[14.0] [IMP] l10n_it_delivery_note: add _get_sync_fields method

---

l10n_it_central_journal_reportlab/__manifest__.py

[14.0][IMP] l10n_it_central_journal_reportlab: aggiunto maintainers

---

l10n_it_delivery_note/models/stock_delivery_note.py

FW-PORT of https://github.com/OCA/l10n-italy/pull/3789
cc: @francesco-ooops

[16.0] [IMP] l10n_it_delivery_note: add _get_sync_fields method

---

assets_management/readme/CONTRIBUTORS.rst
assets_management/report/asset_journal.py
assets_management/report/asset_previsional.py
assets_management/tests/test_assets_management.py

[14.0][FIX] assets_management #3009

---

l10n_it_sdi_channel/models/sdi.py

Semplice correzione in quando l'uso di sudo() è deprecato in questo caso.

[FIX] l10n_it_sdi_channel replace sudo with with_user as deprecated

---

account_vat_period_end_statement/README.rst
account_vat_period_end_statement/__manifest__.py
account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/readme/CONFIGURE.rst
account_vat_period_end_statement/readme/CONTRIBUTORS.rst
account_vat_period_end_statement/readme/DESCRIPTION.rst
account_vat_period_end_statement/static/description/index.html
account_vat_period_end_statement/tests/test_vat_statement.py
account_vat_period_end_statement/views/account_view.xml

Risolve: #2941
Risolve: #2956
Forward port di #2943
Forward port di #2957
--

[16.0] [FIX] account_vat_period_end_statement: previous statement amount

---

l10n_it_withholding_tax_payment/models/withholding_tax.py
l10n_it_withholding_tax_payment/views/withholding_tax.xml

Added new functional field on withholding tax payment move for write comment
--

[16.0][IMP] l10n_it_withholding_tax_payment: added description on withholding tax payment move

---

l10n_it_delivery_note/__manifest__.py

Proposing to add myself and @renda-dev to the list of maintainers for this module.

[IMP] l10n_it_delivery_note: add maintainers

---

l10n_it_central_journal_reportlab/wizard/print_giornale.xml

[14.0][FIX] l10n_it_central_journal_reportlab: utilizzare i data range solo con azienda impostata

---

l10n_it_delivery_note/wizard/delivery_note_create.py

As it was done for #3611
https://github.com/OCA/l10n-italy/issues/3798

[14.0][IMP] l10n_it_delivery_note: add hook to prepare vals needed to create DN

---

l10n_it_delivery_note/views/stock_picking.xml

FW-PORT of https://github.com/OCA/l10n-italy/pull/3803
cc: @francesco-ooops

[16.0] [IMP] l10n_it_delivery_note: picking's dn fields optional in tree view

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
l10n_it_fatturapa_out_oss/wizard/__init__.py
l10n_it_fatturapa_out_oss/wizard/wizard_export_fatturapa.py

https://github.com/OCA/l10n-italy/pull/3818#pullrequestreview-1818364399

[16.0] FIX l10n_it_fatturapa_out: it does not depend on l10n_eu_oss_oca so it can't use oss_country_id

---

l10n_it_account_tax_kind/view/account_tax_view.xml

Risolve https://github.com/OCA/l10n-italy/issues/3893

[14.0] [FIX] l10n_it_account_tax_kind unhide law reference on tax

---

account_vat_period_end_statement/views/account_view.xml
l10n_it_ateco/view/ateco_view.xml
l10n_it_ateco/view/partner_view.xml
l10n_it_central_journal_reportlab/wizard/print_giornale.xml
l10n_it_declaration_of_intent/wizard/select_declarations_view.xml
l10n_it_delivery_note/views/stock_picking.xml
l10n_it_fatturapa/views/account_view.xml
l10n_it_fatturapa_in/views/account_view.xml
l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
l10n_it_fatturapa_sale/views/sale_order_views.xml
l10n_it_intrastat/views/account.xml
l10n_it_withholding_tax_payment/views/withholding_tax.xml

Fix incorrect display of fields with the `nolabel` attribute
--

[16.0] [FIX] nolabel view

---

l10n_it_account_tax_kind/view/account_tax_view.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

[12.0] [FIX] l10n_it_account_tax_kind: unhide law reference on tax

---

l10n_it_abicab/views/abicab_view.xml

Steps:
- install l10n_it_abicab
- install l10n_mx
"ABM Code" field label disappears

[16.0] FIX l10n_it_abicab views incompatibility

---

l10n_it_reverse_charge/__manifest__.py
l10n_it_reverse_charge/models/account_move.py

Risolve https://github.com/OCA/l10n-italy/issues/3581

[16.0][FIX] l10n_it_reverse_charge: fix case there is a line with abbuoni

---

l10n_it_delivery_note/models/stock_delivery_note.py
l10n_it_delivery_note/models/stock_picking.py
l10n_it_delivery_note/tests/test_stock_delivery_note.py
l10n_it_delivery_note/views/stock_delivery_note.xml
l10n_it_delivery_note/wizard/delivery_note_base.py
l10n_it_delivery_note/wizard/delivery_note_create.py

forward-port (and adaptation) of https://github.com/OCA/l10n-italy/pull/3727 to 16.0

[16.0][IMP] l10n_it_delivery_note: filter 'type_id' based on company

---

l10n_it_fatturapa_out/data/invoice_it_template.xml

https://github.com/OCA/l10n-italy/issues/3925

[16.0] FIX l10n_it_fatturapa_out: Unexpected child with tag 'Nome'

---

l10n_it_account_stamp/models/account_move.py

https://github.com/OCA/l10n-italy/issues/3855

[16.0] FIX l10n_it_account_stamp for multi-company env

---

l10n_it_delivery_note/views/stock_picking.xml

Backport of https://github.com/OCA/l10n-italy/pull/3499

[14.0] [FIX] l10n_it_delivery_note: fix picking view

---

l10n_it_withholding_tax/models/account.py
l10n_it_withholding_tax/models/withholding_tax.py
l10n_it_withholding_tax/readme/CONTRIBUTORS.rst
l10n_it_withholding_tax/tests/test_withholding_tax.py

Risolve https://github.com/OCA/l10n-italy/issues/2938 per `12.0`

[FIX] Pagamenti ritenuta d'acconto duplicati

---

l10n_it_account_stamp/models/account_move.py

Risolve https://github.com/OCA/l10n-italy/issues/3855 per `14.0`.
Non ho aggiunto test perché non riesco a riprodurre l'errore in Community.

[FIX] l10n_it_account_stamp error in multi-company env

---

l10n_it_reverse_charge/models/account_invoice.py

To reproduce, just create a refund in reverse charge with "Con autofattura passiva aggiuntiva".
https://github.com/OCA/l10n-italy/issues/2961

[12.0] FIX l10n_it_reverse_charge in case of refunds

---

l10n_it_fatturapa_out/data/invoice_it_template.xml
l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

They could produce rounding discrepancies

[16.0] FIX l10n_it_fatturapa_out : avoind currency conversion when not needed.

---

account_vat_period_end_statement/README.rst
account_vat_period_end_statement/__manifest__.py
account_vat_period_end_statement/models/account.py
account_vat_period_end_statement/readme/CONFIGURE.rst
account_vat_period_end_statement/readme/DESCRIPTION.rst
account_vat_period_end_statement/static/description/index.html
account_vat_period_end_statement/views/account_view.xml

Forward-port of #2385 
Resolves #2956

[14.0][IMP] Implements "Account used for VAT settlement" 

---

l10n_it_declaration_of_intent/models/account_move.py
l10n_it_declaration_of_intent/models/declaration.py
l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
l10n_it_fatturapa_out_di/tests/data/IT06363391001_00001.xml
l10n_it_fatturapa_out_di/tests/data/IT06363391001_00002.xml
l10n_it_fatturapa_out_di/tests/data/IT06363391001_00003.xml

[14.0][FIX]l10n_it_declaration_of_intent:Rimozione required per numero e data documento partner

---

l10n_it_vat_registries/models/account_tax_registry.py
l10n_it_vat_registries/models/vat_registry.py
l10n_it_vat_registries/report/report_registro_iva.xml
l10n_it_vat_registries/views/account_tax_registry_view.xml
l10n_it_vat_registries/wizard/print_registro_iva.py
l10n_it_vat_registries/wizard/print_registro_iva.xml

https://github.com/OCA/l10n-italy/issues/1414

[16.0] IMP l10n_it_vat_registries: ordering option

---

l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py

[14.0][FIX] l10n_it_ricevute_bancarie sostituzione caratteri non ammessi

---

l10n_it_intrastat/__manifest__.py
l10n_it_intrastat/models/account.py
l10n_it_intrastat/security/rules.xml

Otherwise, going to Contabilità > Righe intrastat, user would see data of every company

[16.0] FIX l10n_it_intrastat: multi company for account.invoice.intrastat

---

l10n_it_central_journal_reportlab/wizard/print_giornale.py

https://github.com/OCA/l10n-italy/blob/4c464f4149a37a9e817d1d50b05dd9448fa6e848/l10n_it_central_journal/views/report_account_central_journal.xml#L6C13-L6C66
--

[14.0][REF] l10n_it_central_journal_reportlab: update title like report in "l10n_it_central_journal"

---

l10n_it_split_payment/migrations/14.0.1.0.0/pre-move_split_amount.py

vedi https://github.com/OCA/l10n-italy/commit/228ff64938268e454eb4c66db3ceaf63a4692272#r127965753

[14.0] FIX l10n_it_split_payment migration in case amount_sp already exists (with odoo enterprise)

---

l10n_it_declaration_of_intent/models/account_move.py

[PORT] #2412 to 14.0 l10n_it_declaration_of_intent

---

assets_management/views/asset.xml

Penso andasse inclusa in https://github.com/OCA/l10n-italy/pull/3238.
@sergiocorato puoi dare un'occhiata?

[REF] assets_management: Le righe di ammortamento si aggiornano correttamente

---

l10n_it_vat_registries/models/vat_registry.py

https://github.com/OCA/l10n-italy/issues/4021

[FIX] l10n_it_vat_registries: supplier refund sign

---

l10n_it_fatturapa/models/account.py
l10n_it_fatturapa_out/data/invoice_it_template.xml
l10n_it_fatturapa_out/tests/data/IT06363391001_00017.xml
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py

[14.0] Fix association between lines and related docs

---

l10n_it_intrastat/models/account.py

https://github.com/OCA/l10n-italy/issues/4060

[14.0] [FIX] l10n_it_intrastat: compute weight in case of variants

---

l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py

risolve https://github.com/OCA/l10n-italy/issues/3768 per la 14.0

[14.0] [FIX] l10n_it_fatturapa_in_rc: flag RC in importazione e-fattura con raggruppamento per Aliquota

---

.copier-answers.yml
.github/workflows/stale.yml
.pre-commit-config.yaml

Living on the edge to test https://github.com/OCA/oca-addons-repo-template/pull/248.
> Please update your repo passing `-r HEAD` to copier, and report if it works, before releasing it. Thanks!
_Originally posted by @yajo in https://github.com/OCA/oca-addons-repo-template/issues/248#issuecomment-2004225946_

Update repo template

---

l10n_it_fatturapa/controllers/main.py

[FIX] l10n_it_fatturapa: remove pdf conversion of XML preview

---

l10n_it_delivery_note/models/stock_delivery_note.py

https://github.com/OCA/l10n-italy/issues/4068

[14.0] [FIX] l10n_it_delivery_note: use recipient language

---

l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py

Fix the rework of commit 0315ba5e5a601765552bee38fce4d70a3fd78dcc 
Only action reports must be displayed and not actions.actions
#4055

[16.0] [FIX] l10n_it_fatturapa_out - wizard only reports

---

l10n_it_financial_statements_report/__manifest__.py
l10n_it_financial_statements_report/migrations/16.0.1.0.1/post-migrate.py
l10n_it_financial_statements_report/models/account_account.py
l10n_it_financial_statements_report/tests/__init__.py
l10n_it_financial_statements_report/tests/test_account.py

[FIX] Sezione dei risconti attivi nel bilancio a sezioni contrapposte

---

l10n_it_fatturapa_in/models/account.py
l10n_it_fatturapa_in/tests/data/IT02098391200_FPR16.xml
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py

Risolve https://github.com/OCA/l10n-italy/issues/3523 per `16.0`.
Forward port di #3751.
In #3751 c'è scritto che risolve anche #2465 ma non ho modo di verificarlo perché nella descrizione della issue non ci sono i passi né il file XML per riprodurlo.

[FIX] Fattura elettronica TD01 con totale negativo

---

l10n_it_delivery_note/report/report_delivery_note.xml

To display total prices a setting must be enabled and the DN's type must be "with prices"

[14.0] [FIX] l10n_it_delivery_note: report adjustments

---

l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
l10n_it_intrastat_statement/report/intrastat_mod1_ter.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml

Altrimenti viene ad esempio così: [Modello_INTRA-1_bis1.pdf](https://github.com/OCA/l10n-italy/files/14537716/Modello_INTRA-1_bis1.pdf)

[16.0] [FIX] l10n_it_intrastat_statement: PDF reports not visible

---

l10n_it_fatturapa/README.rst
l10n_it_fatturapa/__manifest__.py
l10n_it_fatturapa/models/__init__.py
l10n_it_fatturapa/models/link_e_invoice_ir_attachment.py
l10n_it_fatturapa/readme/CONTRIBUTORS.md
l10n_it_fatturapa/static/description/index.html
l10n_it_fatturapa_import_zip/README.rst
l10n_it_fatturapa_import_zip/__manifest__.py
l10n_it_fatturapa_import_zip/migrations/16.0.1.1.0/post-migrate.py
l10n_it_fatturapa_import_zip/models/attachment.py
l10n_it_fatturapa_import_zip/readme/CONTRIBUTORS.md
l10n_it_fatturapa_import_zip/static/description/index.html
l10n_it_fatturapa_import_zip/tests/test_import_zip.py
l10n_it_fatturapa_in/README.rst
l10n_it_fatturapa_in/__manifest__.py
l10n_it_fatturapa_in/migrations/16.0.1.1.0/post-migrate.py
l10n_it_fatturapa_in/models/attachment.py
l10n_it_fatturapa_in/readme/CONTRIBUTORS.md
l10n_it_fatturapa_in/static/description/index.html
l10n_it_fatturapa_in/tests/fatturapa_common.py
l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py
l10n_it_fatturapa_out/README.rst
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/migrations/16.0.1.1.0/post-migrate.py
l10n_it_fatturapa_out/models/attachment.py
l10n_it_fatturapa_out/readme/CONTRIBUTORS.md
l10n_it_fatturapa_out/static/description/index.html
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py

Risolve https://github.com/OCA/l10n-italy/issues/3336, https://github.com/OCA/l10n-italy/issues/3623 e https://github.com/OCA/l10n-italy/pull/4100 per `16.0`.

[FIX] Import zip file e-fatture non possibile se non si hanno i diritti da Amministratore. Il sistema rimporta errore generico

---

l10n_it_ricevute_bancarie/wizard/wizard_riba_file_export.py

PR v12 https://github.com/OCA/l10n-italy/pull/2035
Rel: https://github.com/OCA/l10n-italy/issues/2036

[14.0][FW] ricevute bancarie ASCII instead UTF-8

---

l10n_it_fatturapa_out/data/invoice_it_template.xml
l10n_it_fatturapa_out_di/data/invoice_it_template.xml
l10n_it_fatturapa_out_stamp/views/account_invoice_it_dati_bollo.xml
l10n_it_fatturapa_out_wt/views/account_invoice_it_dati_ritenuta.xml

Risolve https://github.com/OCA/l10n-italy/issues/3006 per la 16.0.

[16.0] [FIX] set l10n_it_fatturapa_out XML templates as not translatable

---

l10n_it_riba/models/riba_config.py
l10n_it_riba/tests/riba_common.py
l10n_it_riba/tests/test_riba.py
l10n_it_riba/views/configuration_view.xml

Risolve https://github.com/OCA/l10n-italy/issues/3650 per `16.0`.
Sostituisce https://github.com/OCA/l10n-italy/pull/3668.

[FIX][l10n_it_riba] creazione configurazioni Ri.Ba con utente multicompany

---

l10n_it_declaration_of_intent/models/account_move.py
l10n_it_declaration_of_intent/models/declaration.py
l10n_it_declaration_of_intent/tests/test_declaration_of_intent.py
l10n_it_fatturapa_out_di/tests/data/IT06363391001_00001.xml
l10n_it_fatturapa_out_di/tests/data/IT06363391001_00002.xml
l10n_it_fatturapa_out_di/tests/data/IT06363391001_00003.xml

[16.0] [FIX] l10n_it_declaration_of_intent: use currency.compare_amounts() e rimozione numero documento partner

---

l10n_it_intrastat/models/account.py
l10n_it_intrastat/models/product.py
l10n_it_intrastat/views/product.xml

[16.0][IMP] l10n_it_intrastat: added intrastat country origin on product and category

---

l10n_it_intrastat_statement/__manifest__.py
l10n_it_intrastat_statement/i18n/it.po
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section3.py
l10n_it_intrastat_statement/models/intrastat_statement_purchase_section4.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section3.py
l10n_it_intrastat_statement/models/intrastat_statement_sale_section4.py
l10n_it_intrastat_statement/report/intrastat_mod1_bis.xml
l10n_it_intrastat_statement/report/intrastat_mod1_ter.xml
l10n_it_intrastat_statement/report/report_intrastat_mod1.xml
l10n_it_intrastat_statement/report/report_intrastat_mod1_quater.xml
l10n_it_intrastat_statement/report/report_intrastat_mod1_quinquies.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2_bis.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2_quater.xml
l10n_it_intrastat_statement/report/report_intrastat_mod2_quinquies.xml
l10n_it_intrastat_statement/report/reports.xml
l10n_it_intrastat_statement/static/description/index.html

https://github.com/OCA/l10n-italy/issues/4033
+
https://github.com/OCA/l10n-italy/issues/4247

[16.0] [ADD] quater and quinquies reports for intrastat_mod1 and intrastat_mod2

---

l10n_it_fatturapa/README.rst
l10n_it_fatturapa/demo/account_invoice_fatturapa.xml
l10n_it_fatturapa/readme/CONTRIBUTORS.rst
l10n_it_fatturapa/static/description/index.html
l10n_it_fatturapa_out/__manifest__.py
l10n_it_fatturapa_out/tests/data/IT03297040366_00020.xml
l10n_it_fatturapa_out/tests/data/IT03297040366_00021.xml
l10n_it_fatturapa_out/tests/data/IT03297040366_00022.xml
l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py
l10n_it_fatturapa_out/wizard/efattura.py
requirements.txt

Fix issue #2405
Add validation to company phone number with library phonenumbers

[14.0] l10n_it_fatturapa_out: Add validation to company phone number

---

l10n_it_financial_statements_report/report/financial_statements_report.py
l10n_it_financial_statements_report/report/reports.xml

Cherry pick of https://github.com/OCA/l10n-italy/pull/3601

[16.0][FIX] l10n_it_financial_statements_report: use landscape format for PDF
